### ISSUE TITLE
idrac_firmware firmware is not idempotent

### ISSUE THREAD

**Issue by silvam11** [dell/dellemc-openmanage-ansible-modules#103]
I ran the idrac_firmware module (idrac_firmware) to upgrade firmware for a R640 server and the module failed with the following error:

`{"changed": false, "msg": "'GetRepoBasedUpdateList_OUTPUT'"}`

As the message above does not allow to identify the root cause of the issue, I started debugging the code and I figured out that the issue happens because all the components of my server are already on the firmware versions described by my catalog.xml.

To confirm the root cause, I manually downgraded the firmware versions on my server then I ran the idrac_firmware module which ran successfully. However, if I re-run the module, it fails as the versions were upgraded on the first execution. Therefore, it shows that this module is not idempotent and fails to execute when the state is already present.

Below are some details about the environment:

1. dell openmanage and omsdk are the latest version of devel branches
2. ansible-playbook: 2.8.4
3. python version = 2.7.5
4. IDRAC 9 version 4.10.10.10 (Build 32)

The task is below and it is based on http.:

```
 - name: NEW Update Firmware
    idrac_firmware:
      idrac_ip: "{{ default_idrac_ip }}"
      idrac_user: "{{ default_idrac_user }}"
      idrac_password: "{{ default_idrac_pass }}"
      share_name: "{{ filerepo_service_ip }}/{{ catalog_filePath }}/"
      catalog_file_name: "{{ catalog_fine_name }}"
      apply_update: True
      reboot: True
      job_wait: True
      ignore_cert_warning : True
    register: firmware_update_response
```
