### ISSUE TITLE
dellemc_get_system_inventory  failing on idrac9

### ISSUE THREAD

**Issue by yuji-myst** [dell/dellemc-openmanage-ansible-modules#108]
Hello,
Executing dellemc_get_system_inventory resulted in an error. Do you know the cause and how to deal with it?

Playbook contents
```
---
- hosts: localhost
  tasks:
  - name: Get hardware inventory
    dellemc_get_system_inventory:
      idrac_ip: "{{ check_idrac_status_idrac_ip }}"
      idrac_user: "{{ check_idrac_status_idrac_user }}"
      idrac_password: "{{ check_idrac_status_idrac_password }}"
      idrac_port: "{{ check_idrac_status_idrac_port }}"
```
Error description
```
TASK [Get hardware inventory] *******************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error: unhashable type: 'list'"}
```
iDRAC firmware version version
iDRAC9 version: 3.21.26.22

Can run successfully for this version
iDRAC8 version: 2.70.70.70

Since the following command can be executed successfully for the same iDRAC, we believe that there is no problem with iDRAC.
```
      dellemc_export_lc_logs:
        idrac_ip: "{{ check_idrac_log_idrac_ip }}"
        idrac_user: "{{ check_idrac_log_idrac_user }}"
        idrac_password: "{{ check_idrac_log_idrac_password }}"
        idrac_port: "{{ check_idrac_log_idrac_port }}"
        share_name: "{{ check_idrac_log_share_name }}"
        job_wait: True
```
