### ISSUE TITLE
HTTP error updating firmware using OME

### ISSUE THREAD

**Issue by topzy2000** [dell/dellemc-openmanage-ansible-modules#109]
![error_ome](https://user-images.githubusercontent.com/17653530/76275921-849ddd00-6252-11ea-97c8-841721534f3e.JPG)

![ome playbook](https://user-images.githubusercontent.com/17653530/76276145-1574b880-6253-11ea-8b36-5076cbe95baf.JPG)

Hello,

I get an HTTP error 404 when i try to update a firmware using ome. I attached images of my playbook and the error. I put the correct path to the file on the ansible control node.

Am using iDRAC 9 and firmware 3.21.21.22. Ansible control node is RHEL 8 using python 3.6.8. Kindly assist. Thanks,

-Temi

**Comment by jagadeeshnv** [comment]
@topzy2000 Wanted some details. Can you please let us know the OME version you are using?

**Comment by hvdkooij** [comment]
It seems you are getting closer then I ever got:

```
$ ansible-playbook update-firmware.yaml -i inventory.yml
ERROR! couldn't resolve module/action 'dellemc_ome_fimware'. This often indicates a misspelling, missing collection, or incorrect module path.
```

With a playbook like:
```
---
- hosts: RSA_Netwitness
  connection: local
  gather_facts: False
  tasks:
  - name: Update BIOS
    dellemc_ome_fimware:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      dup_file: "./Updates/BIOS_R6HXJ_WN64_2.6.4.EXE.exe"

```

Oddly enough it works fine for `dellemc.openmanage.dellemc_get_system_inventory:`

My details are:
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxxxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```
