### ISSUE TITLE
Disable Default Password Warning

### ISSUE THREAD

**Issue by spoer78** [dell/dellemc-openmanage-ansible-modules#114]
Hello there,

i am trying to figure out how to disable the password warning for the default idrac admin user "root". I know how to do it via racadm (if installed), but is there a way to do it directly via these ansible roles an the api/redfish without racadm?

Thank you,
sp

**Comment by anupamaloke** [comment]
@spoer78, there are two ways in which you can disable the secure default password warning:

1. use the ```idrac_redfish_config``` module from ```community.general``` ansible-collection and set the iDRAC attribute ```SecureDefaultPassword.1.ForceChangePassword``` to ```False```:

```
  - name: Disable secure default password warning
    community.general.idrac_redfish_config:
      category: Manager
      command: SetManagerAttributes
      resource_id: iDRAC.Embedded.1
      manager_attributes:
        SecureDefaultPassword.1.ForceChangePassword: False
      baseuri: "{{ idrac_ip }}"
      username: "{{ idrac_username}}"
      password: "{{ idrac_password }}"
```
 

2. Create a server configuration profile (SCP) file to set the ```SecureDefaultPassword.1.ForceChangePassword``` to ```False``` and then import it using ```idrac_server_config_profile``` module:

**_scp.xml_**
```
<SystemConfiguration>
        <Component FQDD="iDRAC.Embedded.1">
                <Attribute Name="SecureDefaultPassword.1#ForceChangePassword"">False</Attribute>
        </Component>
</SystemConfiguration>
```

**_Import the scp.xml file_**
```
    - name: Import SCP
      idrac_server_config_profile:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_username }}"
        idrac_password: "{{ idrac_password }}"
        command: "import"
        share_name: "{{ playbook_dir }}"
        scp_file: "scp.xml"
        job_wait: True
```
