### ISSUE TITLE
idrac_firmware failing

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#125]
hello, 
just installed the latest omsdk and latest open manage modules from dev branch
when i run simple playbook i get error that apply_update is not correct parameter.
after removing apply_update it complains that share_mnt is missing. 
im confused what i doing wrong as im following your documentation

```
- name: Update firmware from a repository on a HTTP share.
    idrac_firmware:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_pwd: "{{ idrac_password }}"
      share_name: "http://downloads.dell.com"
      reboot: False
      job_wait: True
      apply_update: True

```
