### ISSUE TITLE
idrac_server_config_profile improvement requested (request)

### ISSUE THREAD

**Issue by ThierryBesancon** [dell/dellemc-openmanage-ansible-modules#137]
Hello

When you export the server config profile with `idrac_server_config_profile`, you can not specify the destination file. You can provide a `scp_file` definition but it is silently ignored. When you read `idrac_server_config_profile.py`, you clearly see the parameter is ignored and the profile is always named `ipaddr_YYYYmmdd_HHMMSS`( extension `.xml` or `.json`). That makes the name quite unpredictable (especially as python ansible is quite slow). Image i want to export the scp as XML, do some xml trickery on it and then push it back with an import. Exporting to an unpredictable name makes like harder in ansible... (unless you have a magic trick to do that that you can share with us?)

So my request is: would it be possible for `idrac_server_config_profile` to export to `ipadd_YYYYmmdd_HHMMSS` by default (to stay compatible with previous releases) but honour `scp_file` when set? If the request is refused, please update the documentation not to be misleading as it is presently: specify that `scp_file` is only used for `import` and never for `export`.

Thanks in advance for your future comment on my request.

**Comment by anupamaloke** [comment]
@ThierryBesancon, thank you for submitting this feature request. While the team will triage this and add to our internal backlog for appropriate prioritization, in the meanwhile, I can think of the following workaround to achieve your workflow:

```
  vars:
    scp_file_name: "scp.xml"

  tasks:
    - name: Export SCP
      idrac_server_config_profile:
        idrac_ip: "{{ inventory_hostname }}"
        idrac_user: "{{ user }}"
        idrac_password: "{{ password }}"
        share_name: "{{ playbook_dir }}"
        export_use: "Clone"
        job_wait: True
      register: result

    - name: state the exported scp file
      stat:
        path: "{{ result.scp_status.file }}"
      register: scp_stat
      delegate_to: localhost

    - name: Rename the scp file
      command: "mv {{ result.scp_status.file }} {{ scp_file_name }}"
      when: scp_stat.stat.exists
      delegate_to: localhost
```
