### ISSUE TITLE
Missing feature in dellemc_configure_idrac_users. Enhancement request.

### ISSUE THREAD

**Issue by ThierryBesancon** [dell/dellemc-openmanage-ansible-modules#139]
Hello

It seems to me that there is no way of getting a list of existent iDRAC users. `dellemc_configure_idrac_users` creates, modifies, removes users but does not return a list of defined users...

Or course, you can get the list of users using a SCP file and then parse the XML/JSON but to do so you need to know the way the information is written in XML/JSON.

Thanks in advance for your analysis of my request.

**Comment by anupamaloke** [comment]
@ThierryBesancon, you can use the following module to get the list of users. I will be closing the request 

```
- name: Get user accounts
  redfish_info:
    baseuri: "{{ idrac_ipaddress }}"
    username: "{{ idrac_user }}"
    password: "{{ idrac_password }}"
    category: "Accounts"
```
