### ISSUE TITLE
Documentation improvement request

### ISSUE THREAD

**Issue by ThierryBesancon** [dell/dellemc-openmanage-ansible-modules#140]
Hello

Thanks for the quite good documentation coming with OMAM. Let's make a step beyond and make it better.

`examples/idrac/idrac_redfish_storage_controller_job_tracking.yml` checks for the completion of a job doing it the low level way with repeatedly calling `uri:`. Why not change this to use `dellemc_get_lc_job_status`?

From
```
    - name: "iDRAC Job tracking"
      uri:
        url: "https://{{ baseuri }}{{ result.task.uri }}"
        user: "{{ username }}"
        password: "{{ password }}"
        method: "GET"
        use_proxy: yes
        status_code: 200, 202
        return_content: yes
        validate_certs: no
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
      register: result
      until: result.json.JobState == 'Completed'
      retries: "{{ retries_count }}"
      delay: "{{ polling_interval }}"
      tags: "{{ all_ctrl_task_tags }}"
```
to
```
    - name: "iDRAC Job tracking"
      dellemc_get_lc_job_status:
        idrac_ip: "{{ idrac_ipaddr }}"
        idrac_user: "{{ username }}"
        idrac_password: "{{ password }}"
        job_id: "{{ result.task.id }}"
      register: result
      until: result.msg.JobStatus == 'Completed'
      retries: "{{ retries_count }}"
      delay: "{{ polling_interval }}"
      tags: "{{ all_ctrl_task_tags }}"
```

Hope it helps. 

Thanks for the examples/samples.
