### ISSUE TITLE
OS deployment using Ansible modules

### ISSUE THREAD

**Issue by SainAbraham** [dell/dellemc-openmanage-ansible-modules#141]
Can we deploy os in multiple poweredge servers at the same time using Ansible modules

**Comment by anupamaloke** [comment]
@SainAbraham, yes you can deploy OS on multiple servers. Please take a look at [idrac_os_deployment](https://github.com/dell/dellemc-openmanage-ansible-modules/blob/devel/library/dellemc/idrac/idrac_os_deployment.py).

```
- name: Boot to Network ISO
  idrac_os_deployment:
      idrac_ip: "192.168.0.1"
      idrac_user: "user_name"
      idrac_password: "user_password"
      share_name: "192.168.0.0:/nfsfileshare"
      share_user: "share_user_name"
      share_password: "share_user_pwd"
      iso_image:  "unattended_os_image.iso"
      expose_duration: 180
```
