### ISSUE TITLE
Dell console login requirement

### ISSUE THREAD

**Issue by kumaresan078** [dell/dellemc-openmanage-ansible-modules#15]
Hi,

I am trying to achieve dell login check via ansible but couldn't get it.We have an requirement to check the dell drac console login authentication via automation through ansible.

Can someone help here? I tried simple "uri" module for web authentication doesn't seems to work.

**Comment by kumaresan078** [comment]
Hi Rajeev,

Thanks for taking up.

Yes i am looking for to automate dell drac web page accessible and verify login authentication.

Regards
Kumaresan

**Comment by anupamaloke** [comment]
@kumaresan078 , I guess you would be best served by running a simple CURL command with the iDRAC credentials to check whether that login is valid or not. Something like below:
```
  tasks:
    - name: Check if iDRAC credentials are valid
      shell: curl --head --silent --compressed https://{{idrac_user}}:{{idrac_pwd}}@{{idrac_ip}}/redfish/v1 -k -L
      register: result

    - name: Fail if not 200OK
      fail:
      when: result.stdout.find("200 OK") == -1
```
