### ISSUE TITLE
idrac_os_deployment : IP Address format is invalid

### ISSUE THREAD

**Issue by soundcha0s** [dell/dellemc-openmanage-ansible-modules#150]
Model: **PowerEdge R6525**
iDRAC Firmware Version: **4.20.20.20**

Hello,

I'm opening this issue as I fail to mount an ISO on a PowerEdge R6525 while it works well on a PowerEdge R640/R630/R620.
This looks similar to [[dellemc_boot_to_network_iso] IP Address format is invalid #56](https://github.com/dell/dellemc-openmanage-ansible-modules/issues/56).

The only difference about the IP addresses in my different cases, is this one is a 10.x.y.z address while others are 172.16.x.y.

**Playbook:**
```
- name: Set the previously generated image as a boot CD
  idrac_os_deployment:
    idrac_ip: "{{ idrac_ip }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    share_name: "{{ nfs_image_path }}"
    iso_image: "{{ paths.dest_iso_image }}"
    expose_duration: 6
```

**Output:**
```
14679     "msg": {
14680         "DeleteOnCompletion": "false", 
14681         "InstanceID": "DCIM_OSDConcreteJob:1", 
14682         "JobName": "BootToNetworkISO", 
14683         "JobStatus": "Failed", 
14684         "Key": "<null_index>", 
14685         "Message": "IP Address format is invalid.", 
14686         "MessageArguments": null, 
14687         "MessageID": "OSD61", 
14688         "Name": "BootToNetworkISO", 
14689         "Status": "Failed", 
14690         "file": "nfs.qhdata.net:/data/nfs-share/debian-netinst.iso", 
14691         "retval": false
14692     }
```

The Lifecycle log also show the following:

```
Detailed Description:
The (installation or configuration) job identified in the message cannot be run. For more information, see the Job Queue.
Recommended Action:
Review the LC Log for related update, configuration, or collection job errors. Retry the operation. If the problem persists, contact your service provider.

```
