### ISSUE TITLE
Exemple in  OMAM_2.1.1_Users_Guide.pdf are not working

### ISSUE THREAD

**Issue by roumano** [dell/dellemc-openmanage-ansible-modules#158]
Exemple in  OMAM_2.1.1_Users_Guide.pdf are not working and haven't been tested at all

Few example of issues : 

# Configure the iDRAC services attributes

Follow example of Page 31 of OMAM_2.1.1_Users_Guide.pdf
```
  - name: Configure the iDRAC services attributes
    dellemc_configure_idrac_services:
      idrac_ip: "xx.xx.xx.xx"
      idrac_user: "xxxx"
      idrac_password: "xxxxxxxx"
      share_name: "xx.xx.xx.xx:/share"
      share_password: "xxxxxxxx"
      share_user: "xxxx"
      share_mnt: "/mnt/share"
      enable_web_server: "Enabled"
      http_port: "80"
      https_port: "443"
      ssl_encryption: "TLS_1_2_Only"
      tls_protocol: "Auto_Negotiate"
      timeout: "1800"
      snmp_enable: "Enabled"
      snmp_protocol: "SNMPv3"
      community_name: "test"
      alert_port: "None"
      discovery_port: "162"
      trap_format: "None"
```

Issue : 
* alert_port : 
```
TASK [Configure the iDRAC services attributes] ***********************************************************************************************************************************
fatal: [epnkvmext3]: FAILED! => {"changed": false, "msg": "argument alert_port is of type <type 'str'> and we were unable to convert to int: <type 'str'> cannot be converted to an int"}
```
remove the alert_port attribut as it's not mandatory

Rerun the ansible playblook :   

* trap_format
```
TASK [Configure the iDRAC services attributes] ***********************************************************************************************************************************
fatal: [epnkvmext3]: FAILED! => {"changed": false, "msg": "value of trap_format must be one of: SNMPv1, SNMPv2, SNMPv3, got: None"}
```

update field trap_format,  

Rerun the ansible playblook :   

* ssl_encryption
```
TASK [Configure the iDRAC services attributes] ***********************************************************************************************************************************
fatal: [epnkvmext3]: FAILED! => {"changed": false, "msg": "value of ssl_encryption must be one of: Auto_Negotiate, T_128_Bit_or_higher, T_168_Bit_or_higher, T_256_Bit_or_higher, got: TLS_1_2_Only"}
```

update field ssl_encryption,  

Rerun the ansible playblook :   

* tls_protocol

```
TASK [Configure the iDRAC services attributes] ***********************************************************************************************************************************
fatal: [epnkvmext3]: FAILED! => {"changed": false, "msg": "value of tls_protocol must be one of: TLS_1_0_and_Higher, TLS_1_1_and_Higher, TLS_1_2_Only, got: Auto_Negotiate"}
```

update the field tls_protocol attribut,  

Rerun the ansible playblook :   
```
TASK [Configure the iDRAC services attributes] ***********************************************************************************************************************************
fatal: [epnkvmext3]: FAILED! => {"changed": false, "msg": "Dell EMC OMSDK library is required for this module"}
```

# Configure iDRAC network settings
Follow example of Page 34 of OMAM_2.1.1_Users_Guide.pdf : Configure iDRAC network settings

```
  tasks:
# Configure iDRAC network Page 32
  - name: Configure iDRAC network settings.
    dellemc.openmanage.idrac_network:
      idrac_ip: "192.168.0.1"
      idrac_user: "user_name"
      idrac_password: "user_password"
      share_name: "192.168.0.1:/share"
      share_password: "share_pwd"
      share_user: "share_user"
      share_mnt: "/mnt/share"
      register_idrac_on_dns: Enabled
      dns_idrac_name: None
      auto_config: Disabled
      static_dns: None
      setup_idrac_nic_vlan: Enabled
      vlan_id: 0
      vlan_priority: 1
      enable_nic: Enabled
      nic_selection: Dedicated
      failover_network: T_None
      auto_detect: Disabled
      auto_negotiation: Enabled
      network_speed: T_1000
      duplex_mode: Full
      nic_mtu: 1500
      ip_address: "192.168.0.1"
      enable_dhcp: Enabled
      enable_ipv4: Enabled
      static_dns_1: "192.168.0.1"
      static_dns_2: "192.168.0.1"
      dns_from_dhcp: Enabled
      static_gateway: None
      static_net_mask: None
```

Same kind of issue :  
```
TASK [Configure iDRAC network settings.] *****************************************************************************************************************************************
fatal: [epnkvmext3]: FAILED! => {"changed": false, "msg": "value of auto_config must be one of: Enabled, Disabled, got: None"}
```

maybe lot of other attribute and other example are not working at all...
