### ISSUE TITLE
idrac_bios : 'NoneType' object has no attribute 'BIOS'

### ISSUE THREAD

**Issue by bvivi57** [dell/dellemc-openmanage-ansible-modules#160]
Hi

When I try to use module "idrac_bios" for change paramater on my server, i have this error

`"module_stderr": "172.18.94.165 : 'NoneType' object has no attribute 'BIOS'\n172.18.94.165 : 'NoneType' object has no attribute 'BIOS'\
`

My playbook is

```
- name: "Bios Parameter"
      idrac_bios:
        idrac_ip: "{{ idrac_ip }}"
        idrac_password: "{{ idrac_password }}"
        idrac_user: "{{ idrac_user }}"
        attributes:
          #DramRefreshDelay: "Performance"
          #ProcVirtualization: "Enabled"
          #ProcCores: "All"
          #ProcPwrPerf: "MaxPerf"
          #MemFrequency: "MaxPerf"
          SysProfile: "PerfOptimized"
```

I use Release 2.1.2 and omsdk-1.2.445 with ansible 2.9.7

My server is PowerEdge R640 

- BIOS Version | 2.8.1
- iDRAC Firmware Version | 4.22.00.00

Thanks for your help
