### ISSUE TITLE
IPV6 not parsed: idrac_server_config_profile

### ISSUE THREAD

**Issue by janr7** [dell/dellemc-openmanage-ansible-modules#162]
Hi

Our IDRAC have both IPV4 and IPV6 configured.
If idrac_ip is configured to used the IP name, itadell135c,, the IPV6 address is looked up and used in the play.

Could you please assist?

If this is used it works as no lookup is needed:  idrac_ip:  "10.145.103.135"
This does not work:
      idrac_ip:       "itadell135c"     ( this looks up the IPV6 and cannot parse )
      idrac_ip:       "2a03:1e80:f803:500:0:0:1000:235"  

Ansible suggests to use ipwrap for IPV6 addresses but does not work with this module.

idrac_ip:        "{{ idrac_ip | ipwrap }}"

Looks like the encapsulating the IPV6 with [] is not happening.
https://2a03:1e80:f804:502::1000:135:443
should look like this?
https://[2a03:1e80:f804:502::1000:135]:443

Model | PowerEdge R740xd
Operating System | SUSE Linux Enterprise Server
Operating System Version | Version 12 SP4 Kernel 4.12.14-95.57-default (x86_64)
BIOS Version | 2.8.2
iDRAC Firmware Version | 4.22.00.53

`
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command": "import",
            "end_host_power_state": "On",
            "export_format": "XML",
            "export_use": "Default",
            "idrac_ip": "itadell135c",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "Laboradmin",
            "job_wait": true,
            "scp_components": "BIOS",
            "scp_file": "itadell1135_bios_scp.xml",
            "share_name": "/tmp",
            "share_password": null,
            "share_user": null,
            "shutdown_type": "Graceful"
        }
    },
    "msg": "Failed to import scp.",
    "scp_status": {
        "Data": {
            "Message": "Failed to execute redfish request: Failed to parse: https://2a03:1e80:f804:502::1000:135:443/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration",
            "Status": "Failed"
        },
        "Message": "none",
        "Status": "Failed",
        "file": "/tmp/itadell1135_bios_scp.xml",
        "retval": true
    }
}
`
`  collections:
    - dellemc.openmanage

  tasks:
  - name: Define the RMB Address
    set_fact:
      idrac_ip:       "itadell135c"
      idrac_user:     "Laboradmin"
      idrac_password: "E267D465E8BE"

  - name: Import Server Configuration BIOS Profile XML from /tmp
    idrac_server_config_profile:
      idrac_ip:        "{{ idrac_ip }}"
      idrac_user:      "{{ idrac_user }}"
      idrac_password:  "{{ idrac_password }}"
      share_name:      "/tmp"
      command:         "import"
`
Thanks so much,
Jan

**Comment by anupamaloke** [comment]
@janr7, I tried the ipwrap filter to wrap the IPv6 address and it properly wraps it in square brackets. 

***[inventory]***
```
[idrac]
FE80:0000:0000:5EFE:0192.0168.0001.0123
```

***[playbook]***
```
  tasks:
    - name: Print IPv6
      debug:
        msg: "{{ inventory_hostname | ansible.netcommon.ipwrap }}"
```

***[playbook run]***
```
$ ansible-playbook ipv6.yml -i hosts

PLAY [idrac] *******************************************************************

TASK [Print IPv6] **************************************************************
ok: [FE80:0000:0000:5EFE:0192.0168.0001.0123] => {
    "msg": "[FE80:0000:0000:5EFE:0192.0168.0001.0123]"
}

PLAY RECAP *********************************************************************
FE80:0000:0000:5EFE:0192.0168.0001.0123 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by Wobak** [comment]
Hi 

I can confirm that the IPv6 works in certain modules but not this one, even in ipwrap.

So it probably needs reviewing : 
```shell
[root@ansible idrac]# cat host_vars/r840/vars.yml
my_user: root
my_pass: xxx
my_ip: 2a03:1e80:f804:502::1000:135
ansible_host: localhost
```

```yaml
---
- name: Get iDRAC info
  hosts: r840
  tasks:
  - name: Get Installed Firmware Inventory
    dellemc_get_firmware_inventory:
        idrac_ip: "{{ my_ip }}"
        idrac_user: "{{ my_user }}"
        idrac_password: "{{ my_pass }}"
    register: result_fw
    delegate_to: localhost

  - name: View specific volume details.
    dellemc_idrac_storage_volume:
      idrac_ip: "{{ my_ip }}"
      idrac_user: "{{ my_user }}"
      idrac_password: "{{ my_pass }}"
      state: "view"
      controller_id: "RAID.Slot.1-1"
      volume_id: "Disk.Virtual.0:RAID.Slot.1-1"
    register: result_sto
    delegate_to: localhost

  - name: Apply Server config profile
    idrac_server_config_profile:
      idrac_ip: "{{ my_ip }}"
      idrac_user: "{{ my_user }}"
      idrac_password: "{{ my_pass }}"
      share_name: "/tmp/"
      command: import
      shutdown_type: "NoReboot"
      scp_file: "r840-thibaut.xml"
      job_wait: "False"
      end_host_power_state: "On"
    delegate_to: localhost
    register: result_config
```


```
[root@ansible idrac]# ansible-playbook idrac_case_problem.yml

PLAY [Get iDRAC info] ****************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************
ok: [r840]

TASK [Get Installed Firmware Inventory] **********************************************************************************************************************************************************************
ok: [r840 -> localhost]

TASK [View specific volume details.] *************************************************************************************************************************************************************************
ok: [r840 -> localhost]

TASK [Apply Server config profile] ***************************************************************************************************************************************************************************
fatal: [r840]: FAILED! => {"msg": "template error while templating string: no filter named 'ansible.netcommon.ipwrap'. String: {{ my_ip | ansible.netcommon.ipwrap }}"}

PLAY RECAP ***************************************************************************************************************************************************************************************************
r840                       : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
