### ISSUE TITLE
ome_smart_fabric   Fabric management is not supported on the specified system

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#179]
I'm not sure if this is related to this module not being idempotent, but I am trying to add a task using ome_smart_fabric to a playbook that will ensure the fabric is configured according to our existing configuration.  I have added all of the required fields to match what we already have setup, so I'm expecting the task to complete with an OK status since it is already present in the exact configuration, but I get an error regardless if I'm running it in check mode or in normal mode.

FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "msg": "Fabric management is not supported on the specified system."}

MX7000 chassis system with 3 chassis in the group.  Version 1.20.10 with design "2xMX9116n_Fabric_Switching_Engines_in_different_chassis"

I was going to have this as the first step of a playbook that will ultimately add VLANs to the uplinks and want to ensure that the fabric is present.  We have had to fully reset our chassis group in the past, so there could be a situation where it would need to create the fabric itself, but normally it would just be verifying that it is present and configured.

If it is because this module only supports the initial creation or an actual modification of the fabric and does not support being idempotent, then that doesn't really fit the standard Ansible model.  I could have a separate playbook just for creating the fabric if we know it is missing, but would be different from every other playbook I've been creating.

**Comment by jagadeeshnv** [comment]
@MallocArray We are looking into it, we will get back in case we need any data.

**Comment by Sajna-Shetty** [comment]
@MallocArray  Could you confirm if you are using an **IP address** or **hostname**?

**Comment by MallocArray** [comment]
@Sajna-Shetty I am using the FQDN hostname of the Lead Chassis.  VIP is not being used in this current configuration.

**Comment by jagadeeshnv** [comment]
@MallocArray This has been addressed with latest release, please verify

**Comment by MallocArray** [comment]
I just tried again after upgrading to the 3.0.0 collection and I still get the same message.  I switched from using variables to hard coded values to ensure I was giving proper data and still get the error

MX7000 running 1.20.10 with an existing Fabric named "Fabric A"

```yml
    - name: Manage SmartFabric
      ome_smart_fabric:
        hostname: "{{ inventory_hostname }}"
        username: "{{ dell_ome_username }}"
        password: "{{ dell_ome_password }}"
        state: present
        name: "Fabric A"
        fabric_design: "2xMX9116n_Fabric_Switching_Engines_in_different_chassis"
        primary_switch_service_tag: "xxxxxxx"
        secondary_switch_service_tag: "xxxxxxx"
        override_LLDP_configuration: "Disabled"
```

FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "msg": "Fabric management is not supported on the specified system."}
