### ISSUE TITLE
ome_firmware - Filter updates by device and component

### ISSUE THREAD

**Issue by TrevorSquillario** [dell/dellemc-openmanage-ansible-modules#239]
Currently when you specify baseline_name it updates ALL devices in the baseline. This is creates a potentially disruptive situation for customers if they don't know this. Creating a separate baseline for each device is the current workaround and it's not the best way to do things, imo. This is not how you would do it in OME.

I would suggest making the module work like OME allowing you to filter the baseline by device and component name. The parameters device_service_tag, device_id could be used with baseline_name. Allowing you to update one device within a baseline and even one component on that device.

**Comment by GregBowersock** [comment]
Adding the ability for a single (or multiple) service tags to run against a baseline would be a huge help. This would allow for people to update a cluster one node at a time to make sure things are working and not require the entire cluster to be offline.

**Comment by dwettstein** [comment]
Actually, I'm a bit surprised that filtering a baseline by device is not possible yet. For us this is absolutely crucial!

**Comment by dperez-sct** [comment]
I have "found" that using idrac instead of openmanage you can upgrade standalone servers. I've used this, if it helps:

```
- dellemc.openmanage.idrac_firmware:
    idrac_ip: "{{ inventory_hostname }}-hwctl"
    idrac_user: "admin"
    idrac_password: "{{ idrac_password }}"
    share_name: "https://downloads.dell.com"
    reboot: True
    job_wait: True
    apply_update: True
```
