### ISSUE TITLE
idrac_firmware.yml HTTP firmware update fails to connect to HTTP server

### ISSUE THREAD

**Issue by anaterth** [dell/dellemc-openmanage-ansible-modules#240]
I am attempting to update the iDRAC via an HTTP server containing the catalog.xml and updates.

My playbook is as follows:

```
- name: Get iDRAC Firmware Version
  connection: local
  hosts: all
  gather_facts: False
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  vars_prompt:
    - name: idrac_password
      prompt: "iDrac Password"


  tasks:
  - name: Update firmware from repository on a HTTP/HTTP/FTP repository
    idrac_firmware:
      idrac_ip: "{{ ansible_host }}"
      idrac_user: "root"
      idrac_pwd: "{{ idrac_password }}"
      share_name: "http://<HTTP server>/updates/"
      catalog_file_name: "catalog.xml"
      share_mnt: "/"
      reboot: True
      job_wait: True
```

When I run this playbook, I get:

```
 fatal: [<iDRAC URL>]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "catalog_file_name": "catalog.xml",
            "idrac_ip": "<iDRAC URL>",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_user": "root",
            "job_wait": true,
            "reboot": true,
            "share_mnt": "/",
            "share_name": "http://<HTTP server>/updates/",
            "share_password": null,
            "share_user": null
        }
    },
    "msg": "Failed to update firmware.",
    "update_status": {
        "@odata.context": "/redfish/v1/$metadata#DellJob.DellJob",
        "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_135163474296",
        "@odata.type": "#DellJob.v1_0_2.DellJob",
        "CompletionTime": "2021-02-16T16:59:12",
        "Description": "Job Instance",
        "EndTime": null,
        "Id": "JID_135163474296",
        "JobState": "Completed",
        "JobType": "RepositoryUpdate",
        "Message": "The specified URI is invalid.",
        "MessageArgs": [
            "NA"
        ],
        "MessageArgs@odata.count": 1,
        "MessageId": "RED005",
        "Name": "Repository Update",
        "PercentComplete": 100,
        "StartTime": "TIME_NOW",
        "Status": "Failed",
        "TargetSettingsURI": null,
        "file": "http://<HTTP server>/updates/catalog.xml",
        "retval": false
    }
}
```
Note: When I run this playbook, I have TCPDump monitoring port 80 on the HTTP server.  I see no traffic.
Another Note: If I navigate to "http://<HTTP server>/updates/catalog.xml" via a browser, I see the catalog.

This seems to indicate it can't pull the catalog.xml, however when I attempt to pull the catalog from the iDRAC CLI, it functions correctly.  Command used:
`racadm update -f catalog.xml -e <HTTP server>/updates -a TRUE -t HTTP`
Note: As before, I have TCPDump monitoring port 80 on the HTTP server.  I see a ton of traffic when I run this.  The job successfully completes as well:
```
racadm>>racadm jobqueue view -i JID_135167066260                                            
---------------------------- JOB -------------------------
[Job ID=JID_135167066260]
Job Name=Repository Update
Status=Completed
Start Time=[Not Applicable]
Expiration Time=[Not Applicable]
Message=[RED001: Job completed successfully.]
Percent Complete=[100]
----------------------------------------------------------
```
