### ISSUE TITLE
dellemc_idrac_storage_volume: Failed to perform storage operation

### ISSUE THREAD

**Issue by akamac** [dell/dellemc-openmanage-ansible-modules#243]
Inventory:
```
ok: [<redacted>] => changed=false
  invocation:
    module_args:
      capacity: null
      controller_id: RAID.Integrated.1-1
      disk_cache_policy: Default
      idrac_ip: <redacted>
      idrac_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      idrac_port: 443
      idrac_user: <redacted>
      media_type: null
      number_dedicated_hot_spare: 0
      protocol: null
      raid_init_operation: null
      raid_reset_config: 'False'
      read_cache_policy: NoReadAhead
      span_depth: 1
      span_length: 1
      state: view
      stripe_size: 65536
      volume_id: null
      volume_type: RAID 0
      volumes: null
      write_cache_policy: WriteThrough
  msg: Successfully completed the view storage volume operation
  storage_status:
    Message:
      RAID.Integrated.1-1:
        ControllerSensor:
          RAID.Integrated.1-1:
            ControllerBattery:
            - Battery.Integrated.1:RAID.Integrated.1-1
        Enclosure:
          Enclosure.Internal.0-1:RAID.Integrated.1-1:
            EnclosureSensor:
              Enclosure.Internal.0-1:RAID.Integrated.1-1: {}
            PhysicalDisk:
            - Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1
            - Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1
            - Disk.Bay.2:Enclosure.Internal.0-1:RAID.Integrated.1-1
            - Disk.Bay.3:Enclosure.Internal.0-1:RAID.Integrated.1-1
            - Disk.Bay.4:Enclosure.Internal.0-1:RAID.Integrated.1-1
            - Disk.Bay.5:Enclosure.Internal.0-1:RAID.Integrated.1-1
    Status: Success
```
Task:
```
- name: configure boot volume
  dellemc_idrac_storage_volume:
    <<: *auth
    state: create
    volume_type: RAID 1
    controller_id: RAID.Integrated.1-1
    volumes:
      - name: root
        drives:
          id:
            - Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1
            - Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1
    capacity: 1000
```
Result:
```
fatal: [<redacted>]: FAILED! => changed=false
  invocation:
    module_args:
      capacity: 1000.0
      controller_id: RAID.Integrated.1-1
      disk_cache_policy: Default
      idrac_ip: <redacted>
      idrac_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      idrac_port: 443
      idrac_user: <redacted>
      media_type: null
      number_dedicated_hot_spare: 0
      protocol: null
      raid_init_operation: null
      raid_reset_config: 'False'
      read_cache_policy: NoReadAhead
      span_depth: 1
      span_length: 1
      state: create
      stripe_size: 65536
      volume_id: null
      volume_type: RAID 1
      volumes:
      - drives:
          id:
          - Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1
          - Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1
        name: root
      write_cache_policy: WriteThrough
  msg: Failed to perform storage operation
```

`redfish_storage_volume` works fine.
