### ISSUE TITLE
Feature request: Add HTTPs boot option to idrac_os_deployment

### ISSUE THREAD

**Issue by liamwh** [dell/dellemc-openmanage-ansible-modules#256]
Or alternatively equivalent to selecting this option in the iDRAC console:

![image](https://user-images.githubusercontent.com/23312359/113446730-bb640980-93f8-11eb-8994-8ea3fec64350.png)

**Comment by anupamaloke** [comment]
@liamwh, in order to boot from a virtual CD/DVD drive using an ISO file from a HTTP/S location, you can maybe use the virtual media. For e.g., following is the sample playbook:

```
 tasks:
  - name: Get virtual media info
    community.general.redfish_info:
      baseuri: "{{ inventory_hostname }}"
      username: "{{ idrac_user }}"
      password: "{{ idrac_password }}"
      category: "Manager"
      command: "GetVirtualMedia"
    delegate_to: localhost

  - name: Insert virtual media
    community.general.redfish_command:
      baseuri: "{{ inventory_hostname }}"
      username: "{{ idrac_user }}"
      password: "{{ idrac_password }}"
      category: "Manager"
      command: "VirtualMediaInsert"
      resource_id: "iDRAC.Embedded.1"
      virtual_media:
        image_url: "http://192.168.10.10/iso/test.iso"
        media_types:
          - CD
          - DVD
    delegate_to: localhost

  - name: Set one-time boot to CD
    community.general.idrac_redfish_config:
      baseuri: "{{ inventory_hostname }}"
      username: "{{ idrac_user }}"
      password: "{{ idrac_passwword }}"
      category: Manager
      command: SetManagerAttributes
      resource_id: iDRAC.Embedded.1
      manager_attributes:
        ServerBoot.1.FirstBootDevice: "VCD-DVD"
    delegate_to: localhost

  - name: Restart server
    dellemc.openmanage.redfish_powerstate:
      baseuri: "{{ inventory_hostname }}"
      username: "{{ idrac_user }}"
      password: "{{ idrac_password }}"
      resource_id: "System.Embedded.1"
      reset_type: "ForceRestart"

  - name: wait for 30 min for OS deployment to finish
    ansible.builtin.wait_for:
      timeout: 1800
    delegate_to: localhost

  - name: Eject virtual media
    community.general.redfish_command:
      baseuri: "{{ inventory_hostname }}"
      username: "{{ idrac_user }}"
      password: "{{ idrac_password }}"
      category: "Manager"
      command: "VirtualMediaEject"
      resource_id: "iDRAC.Embedded.1"
      virtual_media:
        image_url: "http://192.168.10.10/iso/test.iso"
    delegate_to: localhost

```
