### ISSUE TITLE
idrac_network

### ISSUE THREAD

**Issue by ImranJMughal** [dell/dellemc-openmanage-ansible-modules#296]
changing an IP on a idrac from one static address to another fails the task although the Idrac configuration works. Is there a network requirement for the module?  ICMP is not available on our idrac network from the host running the ansible code.

`TASK [Configure the iDRAC network from static/dhcp pool to static] *********************************************************************************************************************************************************
FAILED - RETRYING: Configure the iDRAC network from dhcp to static (3 retries left).
FAILED - RETRYING: Configure the iDRAC network from dhcp to static (2 retries left).
FAILED - RETRYING: Configure the iDRAC network from dhcp to static (1 retries left).
fatal: [idrac]: FAILED! => {"attempts": 3, "changed": false, "msg": "Unable to communicate with iDRAC 10.176.28.26. This may be due to one of the following: Incorrect username or password, unreachable iDRAC IP or a failure in TLS/SSL handshake."}
`

in this instance, I'm moving 10.176.28.26 to 10.176.28.25 . The idrac is available on .25 after the run.

**Comment by ImranJMughal** [comment]
I've tried this on a idrac that is pingable and it works as expected. Is there a flag on the module where we can define the success instead of icmp

**Comment by anupamaloke** [comment]
@ImranJMughal, what are the iDRAC firmware versions? ```idrac_network``` module uses SCP to configure the iDRAC network settings. This module fails if you set the ```job_wait``` option to True since after importing the SCP, it polls iDRAC to check whether the import SCP job has finishes successfully or not. Instead, the best way would be set the ```job_wait``` argument to ```False```, register the output, wait for sometime and then poll the status of the job using the ```idrac_lifecycle_controller_job_info``` module. My recommendation is to use this module only when you are configuring the settings on an older generation of servers that has iDRAC 7 or 8.

If you only have iDRAC 9 and above, then you can use the following module to configure your iDRAC network settings. You will have to install the ```community.general``` Ansible collection from Ansible Galaxy if you have not already installed it. This module does not use SCP to configure the network settings. Instead it uses the Redfish OEM APIs to set the iDRAC attributes (only available in iDRAC 9 and above).

```
  - name: iDRAC network settings
    community.general.idrac_redfish_config:
      baseuri: "{{ baseuri }}"
      username: "{{ username}}"
      password: "{{ password }}"
      category: Manager
      command: SetManagerAttributes
      resource_id: iDRAC.Embedded.1
      manager_attributes:
        "NICStatic.1.DNSDomainName": "{{ dns_domain_name }}"
        "IPv4Static.1.Address": "{{ ipv4_static_address }}"
        "IPv4Static.1.DNS1": "{{ ipv4_static_dns1 }}"
        "IPv4Static.1.DNS2": "{{ ipv4_static_dns2 }}"
        "IPv4Static.1.Gateway": "{{ ipv4_static_gateway }}"
        "IPv4Static.1.Netmask": "{{ ipv4_static_netmask }}"
``` 

HTH
