### ISSUE TITLE
idrac module not available for configuring rsyslog server and port 

### ISSUE THREAD

**Issue by jaichandran** [dell/dellemc-openmanage-ansible-modules#30]
I see in the recent Dell EMC ansible module we not see the module for nabling the rsyslog and configuring the rsyslog server and port configuration . Please appreciate help on this,

**Comment by anupamaloke** [comment]
@jaichandran, we do have the syslog configuration module, but it is currently available in BETA branch.

**Comment by anupamaloke** [comment]
@jaichandran, a bit late but hopefully it will help others too. 
You can use the ```idrac_redfish_config``` [[link]](https://docs.ansible.com/ansible/latest/modules/idrac_redfish_config_module.html) to configure the rsyslog servers and ports:

```
- name: Configure iDRAC syslog server information
  idrac_redfish_config:
    category: Manager
    command: SetManagerAttributes
    manager_attribute_name: "SysLog.1.Server1"
    manager_attribute_value: "192.168.1.2"
    baseuri: "192.168.1.1"
    username: "root"
    password: "calvin"

- name: Configure iDRAC syslog port information
  idrac_redfish_config:
    category: Manager
    command: SetManagerAttributes
    manager_attribute_name: "SysLog.1.Port"
    manager_attribute_value: 514
    baseuri: "192.168.1.1"
    username: "root"
    password: "calvin"

```
I will be closing this issue. If you still face any issue in syslog configuration, please feel free to open a new issue.
