### ISSUE TITLE
idrac_firmware fails when using NFS 

### ISSUE THREAD

**Issue by randy-randerson** [dell/dellemc-openmanage-ansible-modules#301]
##### Question
When trying to update iDRAC firmware using the idrac_firmware ansible module I get the below error: 

```
"msg": "'str' object does not support item assignment"
```

##### Details
I'm connecting to a PowerEdge FC640 iDRAC 9 system with a perpetual enterprise license. I just created a updates repository using the Dell Repository Manager and when I try to connect through the iDRAC web interface to perform a manual update it is able to connect to my repo and see available updates, but when I try using the ansible module I get the above error. 

Here is the playbook I'm using:

```
- name: Update iDRAC firmware
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - dellemc.openmanage
  tasks:
    - name: Update iDRAC firmware
      dellemc.openmanage.idrac_firmware:
        idrac_ip: "10.100.1.81"
        idrac_user: "{{ user }}"
        idrac_password: "{{ password }}"
        share_name: "10.100.1.4:/srv/nfs4/nfsshare/dell_updates/"
        reboot: False
        job_wait: False
        apply_update: False
        catalog_file_name: "FC640_updates_1.03_Catalog.xml"
        share_mnt: "/srv/nfs4/nfsshare/dell_updates/"
```

Here is the traceback when running with -vvv:

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/6h/zmkxssvd35j9n37wqbv86cx80000gp/T/ansible_dellemc.openmanage.idrac_firmware_payload_FiFiP9/ansible_dellemc.openmanage.idrac_firmware_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_firmware.py", line 634, in main
  File "/var/folders/6h/zmkxssvd35j9n37wqbv86cx80000gp/T/ansible_dellemc.openmanage.idrac_firmware_payload_FiFiP9/ansible_dellemc.openmanage.idrac_firmware_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_firmware.py", line 526, in update_firmware_redfish
[WARNING]: Platform darwin on host localhost is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible/2.11/reference_appendices/interpreter_discovery.html for more information.
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "apply_update": false,
            "catalog_file_name": "FC640_updates_1.03_Catalog.xml",
            "idrac_ip": "10.100.1.81",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "root",
            "ignore_cert_warning": true,
            "job_wait": false,
            "reboot": false,
            "share_mnt": "/data/isos/dell_updates/",
            "share_name": "10.100.1.4:/data/isos/dell_updates/",
            "share_password": null,
            "share_user": null
        }
    },
    "msg": "'str' object does not support item assignment"
}
```
 I'm running on ansible 2.11.2 and the latest versions of dellemc.openmanage and omsdk.

Any idea what I might be missing?
