### ISSUE TITLE
ome_template.yml cifs share

### ISSUE THREAD

**Issue by nstallons** [dell/dellemc-openmanage-ansible-modules#306]
##### Question
I don't see any options for using CIFS with the ome_template.yml file?

##### Details
I see options for using NFS in the ome_template.yml file and CIFS in the ome_profile.yml file but there is no explanation in the ome_template.yml file.

**Comment by anupamaloke** [comment]
@nstallons, I am assuming you meant no examples of deploying an OS ISO image from a CIFS share using a CIFS share. If yes, then see below. I will also ask maintainers to update the template examples to add CIFS as well:

```
    - name: "Deploy template and Operating System (OS) on multiple devices"
      ome_template:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        command: "deploy"
        template_id: 12
        device_id:
          - 12765
        device_service_tag:
          - 'SVTG123'
        attributes:
          # Include this to install OS on the devices.
          # This section is optional
          NetworkBootIsoModel:
            BootToNetwork: true
            ShareType: "CIFS"
            IsoTimeout: 1 # allowable values(1,2,4,8,16) in hours
            IsoPath: "/home/iso_path/filename.iso"
            ShareDetail:
              IpAddress: "192.168.0.2"
              ShareName: "sharename"
              User: "share_user"
              Password: "share_password"
          Options:
            EndHostPowerState: 1
            ShutdownType: 0
            TimeToWaitBeforeShutdown: 300
          Schedule:
            RunLater: true
            RunNow: false
```
