### ISSUE TITLE
ome_template modify attributes by name

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#358]
##### Description

Feature Request for the ome_template module to support modifying a template based on the attribute names instead of the ID.  It is cumbersome on the end user to have to look at the API response to find the attribute Id to modify and not sure if these IDs may change between firmware versions, but the names are not likely to change or at least easier to access

Consider reading the playbook
``` yaml
    - name: Modify template attribute values
      # https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/modules/ome_template.rst
      dellemc.openmanage.ome_template:
        hostname: "{{ inventory_hostname }}"
        username: "{{ dell_ome_username }}"
        password: "{{ dell_ome_password }}"
        command: "modify"
        template_name: My Template
        attributes:
          Attributes:
            - Id: 423076
              Value: Enabled
              IsIgnored: false

            - Id: 423757
              Value: Enabled
              IsIgnored: false
```

vs proposed:

```yaml
    - name: Modify template attribute values
      # https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/modules/ome_template.rst
      dellemc.openmanage.ome_template:
        hostname: "{{ inventory_hostname }}"
        username: "{{ dell_ome_username }}"
        password: "{{ dell_ome_password }}"
        command: "modify"
        template_name: My Template
        attributes:
          Attributes:
            - DisplayName: Secure Boot
              Value: Enabled
              IsIgnored: false

            - DisplayName: NICStatic 1 DNS Domain From DHCP
              Value: Enabled
              IsIgnored: false
```
##### New or existing component

ome_template

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
