### ISSUE TITLE
Collection 5.0.0 breaking ome_application_network_time and ome_application_network_proxy

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#360]
##### Summary

After upgrading to collection 5.0.0 and adding validate_certs: false, these two modules continue to fail with an unhelpful message.
ome_application_network_time
ome_application_network_proxy
```
FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "msg": "'validate_certs'"}
```
I've confirmed that validate_certs is set to false and all other tasks in my playbook can run if I skip these two.  

##### Component Name

ome_application_network_time
ome_application_network_proxy

##### Ansible Version

```paste below
ansible 2.10.17.post0
  config file = /runner/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]


omsdk (1.2.456) and 1.2.488
```

##### iDRAC or OpenManage Enterprise version

Tested against OME-M 1.30.10 and 1.40.10 as well as OME 3.8

##### Playbook used

```yaml
    - name: Configure NTP server for time synchronization.
      dellemc.openmanage.ome_application_network_time:
        hostname: "{{ inventory_hostname }}"
        username: "{{ dell_ome_username }}"
        password: "{{ dell_ome_password }}"
        validate_certs: "{{ dell_validate_certs | default(omit) }}"
        ca_path: "{{ dell_ca_path | default(omit) }}"
        time_zone: "{{ ntp_config.time_zone }}"
        enable_ntp: true
        primary_ntp_address: "{{ ntp_config.primary }}"
        secondary_ntp_address1: "{{ ntp_config.secondary1 }}"
        secondary_ntp_address2: "{{ ntp_config.secondary2 }}"
      tags:
        - ntp


    - name: Proxy configuration
      dellemc.openmanage.ome_application_network_proxy:
        hostname: "{{ inventory_hostname }}"
        username: "{{ dell_ome_username }}"
        password: "{{ dell_ome_password }}"
        validate_certs: "{{ dell_validate_certs | default(omit) }}"
        ca_path: "{{ dell_ca_path | default(omit) }}"
        enable_proxy: true
        ip_address: "{{ proxy_config.address }}"
        proxy_port: "{{ proxy_config.port }}"
        enable_authentication: false
      tags:
        - proxy
```

##### Expected Results

Task would run as it did with 4.4.0 and return OK as values are already set

##### Actual Results

```
The full traceback is:
  File "/tmp/ansible_dellemc.openmanage.ome_application_network_time_payload_6gd0yc7d/ansible_dellemc.openmanage.ome_application_network_time_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/ome_application_network_time.py", line 254, in main
  File "/tmp/ansible_dellemc.openmanage.ome_application_network_time_payload_6gd0yc7d/ansible_dellemc.openmanage.ome_application_network_time_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/ome_application_network_time.py", line 168, in get_payload
  File "/tmp/ansible_dellemc.openmanage.ome_application_network_time_payload_6gd0yc7d/ansible_dellemc.openmanage.ome_application_network_time_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/ome_application_network_time.py", line 168, in <listcomp>
fatal: [dellchassis.domain.com]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_path": null,
            "enable_ntp": true,
            "hostname": "dellchassis.domain.com",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "primary_ntp_address": "ntp-wdc.domain.com",
            "secondary_ntp_address1": "ntp-ssh.domain.com",
            "secondary_ntp_address2": "x.x.x.x",
            "system_time": null,
            "time_zone": "TZ_ID_11",
            "timeout": 30,
            "username": "serviceaccount@domain.com",
            "validate_certs": false
        }
    },
    "msg": "'validate_certs'"
}


The full traceback is:
  File "/tmp/ansible_dellemc.openmanage.ome_application_network_proxy_payload_z_6rqze1/ansible_dellemc.openmanage.ome_application_network_proxy_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/ome_application_network_proxy.py", line 242, in main
  File "/tmp/ansible_dellemc.openmanage.ome_application_network_proxy_payload_z_6rqze1/ansible_dellemc.openmanage.ome_application_network_proxy_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/ome_application_network_proxy.py", line 188, in get_payload
  File "/tmp/ansible_dellemc.openmanage.ome_application_network_proxy_payload_z_6rqze1/ansible_dellemc.openmanage.ome_application_network_proxy_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/ome_application_network_proxy.py", line 188, in <listcomp>
fatal: [dellchassis.domain.com]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_path": null,
            "enable_authentication": false,
            "enable_proxy": true,
            "hostname": "dellchassis.domain.com",
            "ip_address": "x.x.x.x",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_password": null,
            "proxy_port": 80,
            "proxy_username": null,
            "timeout": 30,
            "username": "serviceaccount@domain.com",
            "validate_certs": false
        }
    },
    "msg": "'validate_certs'"
}
```

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
  to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, 
  they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
