### ISSUE TITLE
Documentation insufficent for first use

### ISSUE THREAD

**Issue by cacack** [dell/dellemc-openmanage-ansible-modules#37]
Trying this out for the first time and the documentation seems to be missing something related to setting everything up.  I setup a new virtualenv for this, installed ansible, OMSDK and then this ansible module.  But this results in a failed task stating "Dell EMC OMSDK library is required for this module".

What am I missing?

Below is the details on what I ran on an Ubuntu Xenial system with the latest updates:
```
cd ~
mkdir ~/virtualenv
sudo apt-get update
sudo apt-get install -y python-dev python-pip libffi-dev virtualenv build-essential
# ensure latest pip and setuptools
sudo python -m pip install -U pip
sudo pip install -U setuptools
virtualenv ~/virtualenv/dell-ansible
source ~/virtualenv/dell-ansible/bin/activate

# install ansible
pip install ansible

# install omsdk
cd ~/devel/others
git clone https://github.com/dell/omsdk.git
cd omsdk
pip install -r requirements-python2x.txt
sh build.sh 1.2 345
cd dist
pip install omsdk-1.2.345-py2.py3-none-any.whl

# install dellemc-openmanage-ansible-modules
cd ~/devel/others
git clone https://github.com/dell/dellemc-openmanage-ansible-modules.git
dellemc-openmanage-ansible-modules
python install.py
```

Playbook:
```
---

- hosts: all
  connection: local
  name: Gather firmware inventory
  gather_facts: false

  tasks:

    - name: Get Installed Firmware Inventory
      dellemc_get_firmware_inventory:
        idrac_ip: "{{ inventory_hostname }}"
        idrac_user: "{{ drac_username }}"
        idrac_pwd: "{{ drac_password }}"
```

Invocation:
```
~/virtualenv/dell-ansible/bin/ansible-playbook \
  -i "${DRAC_HOSTNAME}," \
  --extra-vars="drac_username=${DRAC_USERNAME} drac_password=${DRAC_PASSWORD}" \
  drac_firmware_inventory.yml
```

Output:
```
PLAY [Gather firmware inventory] **************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Get Installed Firmware Inventory] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [drac_hostname_redacted]: FAILED! => {"changed": false, "msg": "Dell EMC OMSDK library is required for this module"}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
drac_hostname_redacted   : ok=0    changed=0    unreachable=0    failed=1
```
