### ISSUE TITLE
Dell_emc_idrac_users

### ISSUE THREAD

**Issue by zeze92** [dell/dellemc-openmanage-ansible-modules#40]
Playbook
---
- hosts: all
  connection: local
  name: Configure the iDRAC users attributes
  gather_facts: False

  tasks:
  - name: Configure the create iDRAC users attributes
    dellemc_configure_idrac_users:
       idrac_ip:   "x.x.x.x"
       idrac_user: "root"
       idrac_pwd:  "calvin"
      share_name: "/NFS"
       share_name: "x.x.x.x:/TEST_NFS"
       share_mnt: "/mnt/share"
       action: "create"
       user_name: "user_name"
       user_password: "user_pwd"
       privilege_users: 'Administrator'
       ipmilanprivilege_users: 'Operator'
       ipmiserialprivilege_users: 'Administrator'
       enable_users: 'Enabled'
       solenable_users: 'Enabled'
       protocolenable_users: 'Enabled'
       privacyprotocol_users: 'DES'
       authenticationprotocol_users: 'MD5'

_TASK [Configure the create iDRAC users attributes] ***************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "returned status code doesn't match with the expected success code"}
fatal: [10.23.156.24]: FAILED! => {"changed": false, "msg": "[Errno 2] No such file or directory: '/mnt/share/scpoviiyr.xml1'"}_

**Comment by zeze92** [comment]
The problem is for FC640 with firmware : 
 iDRAC with Lifecycle Controller => 3.21.21.21

**Comment by anupamaloke** [comment]
@zeze92, it looks like the share_mnt path is incorrect. I would suggest you to not use 'share_mnt' but use the local path on ansible controller. In iDRAC firmware version < 2.50.50.50, 'share_mnt' argument is required for writing a SCP to NFS/CIFS share and then importing the SCP from that CIFS/NFS share. However, in iDRAC firmware > 2.50.50.50, we support local file streaming. So, 'share_mnt' argument is optional. Instead, you can provide a local path to the 'share_name' argument

For e.g  see the following playbook:

```
tasks:
  name: Configure the create iDRAC users attributes
  dellemc_configure_idrac_users:
    idrac_ip:  "192.168.10.10"
    idrac_user:  "root"
    idrac_pwd:  "calvin"
    share_name:  "{{ playbook_dir }}"
    action:  "create"
    user_name:  "user_name"
    user_password:  "user_pwd"
    privilege_users:  'Administrator'
    ipmilanprivilege_users:  'Operator'
    ipmiserialprivilege_users:  'Administrator'
    enable_users:  'Enabled'
    solenable_users:  'Enabled'
    protocolenable_users:  'Enabled'
    privacyprotocol_users:  'DES'
    authenticationprotocol_users:  'MD5'
```
