### ISSUE TITLE
NTP - network share required

### ISSUE THREAD

**Issue by ghost** [dell/dellemc-openmanage-ansible-modules#409]
##### Question
Why is network share required?!

**Comment by anupamaloke** [comment]
@nikoloskid, it is a legacy argument that was added in v1.0 since that supported legacy iDRAC firmware versions that did not support importing a SCP using a import buffer but only from a remote file share (NFS, CIFS etc.). 

You can simply set it to `{{ playbook_dir }}` or any other local file path in your task:

```
- name: Configure time zone and NTP on iDRAC
  dellemc.openmanage.idrac_timezone_ntp:
       idrac_ip:   "190.168.0.1"
       idrac_user: "user_name"
       idrac_password:  "user_password"
       ca_path: "/path/to/ca_cert.pem"
       share_name: "{{ playbook_dir }}"
       setup_idrac_timezone: "UTC"
       enable_ntp: Enabled
       ntp_server_1: "190.168.0.1"
       ntp_server_2: "190.168.0.2"
       ntp_server_3: "190.168.0.3"
```
