### ISSUE TITLE
VNC enable / disable

### ISSUE THREAD

**Issue by chaosblog** [dell/dellemc-openmanage-ansible-modules#44]
Is there a possibility to enable or disable IDRAC-VNC via Ansible?

**Comment by anupamaloke** [comment]
@chaosblog, you can use the [idrac_redfish_config](https://github.com/ansible/ansible/blob/stable-2.8/lib/ansible/modules/remote_management/redfish/idrac_redfish_config.py) module to do so. You need to make sure that you are at least using Ansible version 2.8. See below for example playbook:

```
  - name: Set VNC server to Enabled in iDRAC
    idrac_redfish_config:
      category: Manager
      command: SetManagerAttributes
      manager_attribute_name: VNCServer.1.Enable
      manager_attribute_value: "Enabled"
      baseuri: "192.168.1.1"
      username: "root"
      password: "calvin"
```
