### ISSUE TITLE
SCP import fails via CIFS

### ISSUE THREAD

**Issue by qwertzlbert** [dell/dellemc-openmanage-ansible-modules#45]
Importing a SCP fails when using a CIFS share. Importing from local works. 
Importing via WebGUI works.

# Details

System: R7415
iDRAC version: 3.30.30.30
BIOS: 1.7.6

inventory:
```
all:
  children:
    servers:
      hosts:
        c1-drac:
          baseuri: "10.113.0.46"
        update_share:
        # only smb/cifs is supported by this playbooks atm!
          username: "user1"
          password: "password"
          path: '\\10.113.0.244\firmware'
          catalog: 'opx-lab\BasicDeploymentFirmware_1.00_Catalog.xml'
        deployment: "local"
```

task:
```
- name: update System (14G) - upload update-SCP to iDRAC
  when: ansible_facts[baseuri]['SystemInventory']['System'][0]['SystemGeneration'] == "14G Monolithic"
  dellemc_idrac_server_config_profile: 
    command: import
    idrac_ip: "{{ baseuri }}"
    idrac_user: "{{ user }}"
    idrac_pwd: "{{ password }}"
    share_name: "{{ update_share['path'] }}"
    share_user: "{{ update_share['username'] }}"
    share_pwd: "{{ update_share['password'] }}"
    scp_file: "{{ ansible_facts[baseuri]['SystemInventory']['System'][0]['ServiceTag'] }}-scp.xml"
    scp_components: "ALL"
    job_wait: "True"
    shutdown_type: "Forced"
  register: result
  until: result is changed
  retries: 3
  delay: 10
  delegate_to: localhost
```
Error Message:
```
FAILED - RETRYING: update System (14G) - upload update-SCP to iDRAC (1 retries left).Result was: {
    "attempts": 3, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "command": "import", 
            "end_host_power_state": "On", 
            "export_format": "XML", 
            "export_use": "Default", 
            "idrac_ip": "10.113.0.46", 
            "idrac_port": 443, 
            "idrac_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "idrac_user": "root", 
            "job_wait": true, 
            "scp_components": "ALL", 
            "scp_file": "90YSGL2-scp.xml", 
            "share_name": "\\\\10.113.0.244\\firmware", 
            "share_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "share_user": "user1", 
            "shutdown_type": "Forced"
        }
    }, 
    "msg": "Failed to import scp.", 
    "retries": 4, 
    "scp_status": {
        "Data": {
            "Message": "returned status code doesn't match with the expected success code", 
            "Status": "Failed", 
            "StatusCode": 400
        }, 
        "Message": "none", 
        "Status": "Failed", 
        "StatusCode": 400, 
        "error": {
            "error": {
                "@Message.ExtendedInfo": [
                    {
                        "Message": "The property Username is a required property and must be included in the request.", 
                        "MessageArgs": [
                            "Username"
                        ], 
                        "MessageArgs@odata.count": 1, 
                        "MessageId": "Base.1.2.PropertyMissing", 
                        "RelatedProperties": [
                            "Username"
                        ], 
                        "RelatedProperties@odata.count": 1, 
                        "Resolution": "Ensure that the property is in the request body and has a valid value and resubmit the request if the operation failed.", 
                        "Severity": "Warning"
                    }
                ], 
                "code": "Base.1.2.GeneralError", 
                "message": "A general error has occurred. See ExtendedInfo for more information"
            }
        }, 
        "file": "\\\\10.113.0.244\\firmware\\90YSGL2-scp.xml", 
        "retval": true
    }
}
```

# Repro Steps
Allways
