### ISSUE TITLE
[FEATURE]:Virtual Media support in idrac_boot

### ISSUE THREAD

**Issue by squigit** [dell/dellemc-openmanage-ansible-modules#457]
**Describe the solution you'd like**
The idrac_boot module supports a number of static sources and pxe, but does not support virtual cd as a section choice for boot source override.  This would be useful now that the virtual_media module has been released in 6.3.0.

**Comment by sachin-apa** [comment]
@squigit Thanks for posting a feature request.

  **_idrac_boot_** supports booting from virtual media, please use the below playbook to do the same, the module also takes care of rebooting the iDRAC

```
  - name: Configure boot source override mode.
    idrac_boot:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: false
      boot_source_override_target: cd
      boot_source_override_enabled: once
    tags: virtual-cd
```

Let us know in case any questions. we will close this based on your response.

@anupamaloke
