### ISSUE TITLE
[BUG]: https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/EXECUTION_ENVIRONMENT.md

### ISSUE THREAD

**Issue by ffirg** [dell/dellemc-openmanage-ansible-modules#459]
### Bug Description

Formatting and syntax of the example AAP custom credential doesn't work OOTB

Suggest changing the *input configuration* to this (AAP 2.3 pre-GA validates this) under https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/EXECUTION_ENVIRONMENT.md#create-credential-types:

```
fields:
  - id: username
    type: string
    label: Username
  - id: password
    type: string
    label: Password
    secret: true
required:
  - username
  - password
```

### Component or Module Name

EE readme

### Ansible Version

n/a

### Python Version

n/a

### iDRAC/OME/OME-M version

n/a

### Operating System

n/a

### Playbook Used

n/a

### Logs

n/a

### Steps to Reproduce

n/a

### Expected Behavior

saves in AAP successfully

### Actual Behavior

syntax errors and won't save
