### ISSUE TITLE
[BUG]: syntax for example playbook https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/EXECUTION_ENVIRONMENT.md#use-ansible-runner-to-verify-the-execution-environment

### ISSUE THREAD

**Issue by ffirg** [dell/dellemc-openmanage-ansible-modules#460]
### Bug Description

Example under 3. Create a playbook. has syntax problems and also doesn't pass ansible-lint checks.

Suggest changing to:

```
---
- hosts: idrac
  connection: local
  name: Get system inventory
  gather_facts: false

  collections:
  - dellemc.openmanage

  tasks:
  - name: Get system inventory.
    idrac_system_info:
      idrac_ip: "{{ inventory_hostname  }}"
      idrac_user: "{{ user }}"
      idrac_password: "{{ password }}"
      validate_certs: false
```

### Component or Module Name

n/a

### Ansible Version

n/a

### Python Version

n/a

### iDRAC/OME/OME-M version

n/a

### Operating System

n/a

### Playbook Used

n/a

### Logs

n/a

### Steps to Reproduce

n/a

### Expected Behavior

runs successfully

### Actual Behavior

syntax errors
