### ISSUE TITLE
How to Update from ftp.dell.com

### ISSUE THREAD

**Issue by fxfitz** [dell/dellemc-openmanage-ansible-modules#47]
We are currently attempting to use these modules to update our iDrac firmware from ftp.dell.com.  To do that we needed to use the fw_update_url branch which is fine, however our problem is that ftp.dell.com has a gzipped Catalog.xml file (specifically, `Catalog.xml.gz`). 

Is it possible to build this functionality into the module so we can just use this to update from the official Dell updates?

**Comment by anupamaloke** [comment]
@fxfitz, thank you for sharing this requirement. We are actively looking into this request.

**Comment by anupamaloke** [comment]
@fxfitz, I just pushed in the ```idrac_firmware``` module in the ```fw_update_url``` branch that contains the changes to update the firmware from Dell online repository. You can now run the following playbook:

```
  - name: firmware_update
    idrac_firmware:
      idrac_ip :  "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password:  "{{ idrac_password }}"
      share_name: "http://downloads.dell.com/catalog"
      catalog_file_name: "Catalog.xml"
      apply_update: False
      reboot: False
      job_wait: True
```
