### ISSUE TITLE
by default "Alerts are turned off" in iDrac

### ISSUE THREAD

**Issue by bobykus31** [dell/dellemc-openmanage-ansible-modules#477]
Since by default "Alerts are turned off" in iDrac  Version 6.10.30.00(Build 29), no logs are shipping to syslog server even the configuration of  remote log server is correct

```
    dellemc.openmanage.idrac_attributes:
      ..... 
        SysLog.1.SysLogEnable: "Enabled"
        SysLog.1.Server1: "rsyslog.my.ip"
        SysLog.1.Port: "1"
```
How it is possible to change "Alerts:  Alerts are turned off. No alerts will be generated." setting to "Alerts: Alerts are enabled."

Configuration >  Alert Configuration >  Alerts

with ansible  _dellemc.openmanage.idrac_attributes_ ? Is it even possible?
