### ISSUE TITLE
[QUESTION]: idrac_server_config_profile import problem

### ISSUE THREAD

**Issue by sp33dyS** [dell/dellemc-openmanage-ansible-modules#479]
Hi. We've got a problem when trying to import profile template file, using **_idrac_server_config_profile_**, with changes we want to apply in iDRAC.
Job in Ansible Tower performs well, but ends with **Changes found to be applied**.
Similar situation happens when trying to create new user using **_idrac_user_** module. Job ends with **Changes found to commit** message.
We've tried different module settings and both JSON and XML files. Nothing works.
We've found nothing helpful in configuration about this issue.

Python 3.9.16
Ansible Core 2.14.2
Ansible Tower 3.8.4
Dell EMC OpenManage Ansible Modules 6.3.0
iDRAC firmware 6.0

**Comment by anupamaloke** [comment]
@sp33dyS, could you please share your playbook?

**Comment by sp33dyS** [comment]
Hi, thank you for reply.
My playbook looks like this:
```
---
- hosts: 127.0.0.1
  gather_facts: no
  strategy: linear
  become: no

  tasks:

    - debug:
        msg:
          - ================================
          - Test_openmanage.yml
          - ================================
      tags:
        - always

    - name: Import SCP with IDRAC components in JSON format from a local path
      dellemc.openmanage.idrac_server_config_profile:
        idrac_ip: "x.x.x.x"
        idrac_user: "root"
        idrac_password: "xxxxxxxxxx"
        command: import
        share_name: "scp"
        scp_file: idrac_conf.json
        #scp_file: idrac_conf_full.json
        #scp_file: idrac_conf.xml
        export_format: "JSON"
        validate_certs: False
        shutdown_type: Graceful
        end_host_power_state: "On"
        job_wait: False
```

Also task for _idrac_user_ module:
```
    - name: Import SCP with IDRAC components in JSON format from a local path
      dellemc.openmanage.idrac_user:
        idrac_ip: x.x.x.x
        idrac_user: root
        idrac_password: xxxxxxxxxx
        user_name: test
        user_password: test_password
        privilege: ReadOnly
        enable: true
        validate_certs: false
```
