### ISSUE TITLE
[BUG]: Cannot tweak IPv6 attributes on iDRAC 8

### ISSUE THREAD

**Issue by mreho** [dell/dellemc-openmanage-ansible-modules#488]
### Bug Description

Cannot tweak IPv6 attributes on iDRAC 8 using the idrac_attributes module, which works just fine on iDRAC 9.

The ExportSystemConfiguration endpoint of this iDRAC 8 returns the following :
```
    { "Name": "IPv6.1#Enable",
      "Value": "Disabled",
      "Set On Import": "True",
      "Comment": "Read and Write" },
    { "Name": "IPv6.1#AutoConfig",
      "Value": "Disabled",
      "Set On Import": "True",
      "Comment": "Read and Write" },
```

So I use `IPv6.1.Enable` and `IPv6.1.AutoConfig` parameters but the playbook fails.

### Component or Module Name

idrac_attributes

### Ansible Version

2.14.3

### Python Version

3.10.6

### iDRAC/OME/OME-M version

iDRAC 8 v2.83.83.83

### Operating System

Ubuntu 22.04.2 LTS

### Playbook Used

```
  - name: Network
    idrac_attributes:
      idrac_ip: "{{ ipmi_ipv4 }}"
      idrac_user: "{{ username }}"
      idrac_password: "{{ password }}"
      ca_path: files/myca.pem
      validate_certs: false
      idrac_attributes:
        IPv4Static.1.DNSFromDHCP: Enabled
        IPv6.1.Enable: Enabled
        IPv6.1.AutoConfig: Disabled
        NIC.1.DNSRacName: "{{ ipmi_hostname }}"
        NICStatic.1.DNSDomainFromDHCP: Enabled
        NIC.1.DNSRegister: Enabled
```

### Logs

```
fatal: [myhostname.mydomain.tld]: FAILED! => {
    "changed": false,
    "invalid_attributes": {
        "IPv6.1.AutoConfig": "Attribute does not exist.",
        "IPv6.1.Enable": "Attribute does not exist."
    },
    "invocation": {
        "module_args": {
            "ca_path": "files/myca.pem",
            "idrac_attributes": {
                "IPv4Static.1.DNSFromDHCP": "Enabled",
                "IPv6.1.AutoConfig": "Disabled",
                "IPv6.1.Enable": "Enabled",
                "NIC.1.DNSRacName": "myhostname",
                "NIC.1.DNSRegister": "Enabled",
                "NICStatic.1.DNSDomainFromDHCP": "Enabled"
            },
            "idrac_ip": "10.0.0.1",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "myuser",
            "lifecycle_controller_attributes": null,
            "resource_id": null,
            "system_attributes": null,
            "timeout": 30,
            "validate_certs": false
        }
    },
    "msg": "Attributes have invalid values."
}

```

### Steps to Reproduce

Run this task

### Expected Behavior

Expected to be working, status [ok] or [changed]

### Actual Behavior

[failed]
