### ISSUE TITLE
[BUG]: Module dellemc.openmanage.ome_firmware hangs on execution

### ISSUE THREAD

**Issue by sbeyermann** [dell/dellemc-openmanage-ansible-modules#494]
### Bug Description

I try to upgrade the firmware of one certain Dell PowerEdge R750 server using the dellemc.openmanage collection. I use the dellemc.openmanage.ome_firmware module to achieve this with the below task. However on execution of the playbook the execution stops when the firmware update should be started. It does not abort with an error message nor does it terminate after the default 30s.

I already used other modules like dellemc.openmanage.ome_device_info that worked fine. So the basic communication between my ansible host and Dell OpenManage Enterprise should not be an issue.

Although I opened this as a bug report I definitely won't rule out a user error :smile: 

### Component or Module Name

dellemc.openmanage.ome_firmware from collection dellemc.openmanage:7.4.0

### Ansible Version

ansible 2.14.4

### Python Version

Python 3.9.2

### iDRAC/OME/OME-M version

Dell OpenManage Enterprise 3.10.0

### Operating System

Debian 11.6

### Playbook Used

playbook-test-firmware.yml
```
  tasks:
  - name: Update firmware of one specific device
    dellemc.openmanage.ome_firmware:
      hostname: myome.company.com
      username: admin
      password: somepassword
      validate_certs: false
      baseline_name: R750General
      device_id:
        - 10165
    delegate_to: localhost
```

### Logs

```
TASK [Update firmware of one specific device] ********************************************************************************************************************************************************************************************
task path: /scripts/ansible/pod/playbook-test-firmware.yml:43
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1681284969.390742-210-67254126161417 `" && echo ansible-tmp-1681284969.390742-210-67254126161417="` echo /root/.ansible/tmp/ansible-tmp-1681284969.390742-210-67254126161417 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/dellemc/openmanage/plugins/modules/ome_firmware.py
<localhost> PUT /root/.ansible/tmp/ansible-local-206iya4s_98/tmpfxbwszls TO /root/.ansible/tmp/ansible-tmp-1681284969.390742-210-67254126161417/AnsiballZ_ome_firmware.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1681284969.390742-210-67254126161417/ /root/.ansible/tmp/ansible-tmp-1681284969.390742-210-67254126161417/AnsiballZ_ome_firmware.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1681284969.390742-210-67254126161417/AnsiballZ_ome_firmware.py && sleep 0'
```
On this point the script simply hangs (does not stop/terminate/timeout). I do see logins happening in the OME audit log, but no firmware update jobs are being created on OME or in the iDRAC job-queue of the target server.

### Steps to Reproduce

This is no intermittent issue. It happens every time I execute the above playbook/task

I already tried multiple variation of the above task, with and without check_mode enabled:
- Using the service tag instead of the device-id:
```
  tasks:
  - name: Update firmware of one specific device
    dellemc.openmanage.ome_firmware:
      hostname: myome.company.com
      username: admin
      password: somepassword
      validate_certs: false
      baseline_name: R750General
      device_service_tag:
        - ABCDEFG
    delegate_to: localhost
```
- Using a device/component combination
```
  - name: Update firmware of one specific device
    dellemc.openmanage.ome_firmware:
      hostname: myome.company.com
      username: admin
      password: somepassword
      validate_certs: false
      baseline_name: R750General
      devices:
        - id: 10165
          components: PowerEdge Server BIOS
    delegate_to: localhost
```
Each test led to the same result, the module silently hangs and does not perform any operations.

### Expected Behavior

The module dellemc.openmanage.ome_firmware should create a firmware update job on OME which in turn does upgrade the firmware of the target device (identified by id or by service tag). If anything goes wrong, e. g. a unknown firmware baseline, it should display an according error message

### Actual Behavior

The module dellemc.openmanage.ome_firmware hangs and does not do anything besides logging in to OME
