### ISSUE TITLE
Is VRTX CMC supported ?

### ISSUE THREAD

**Issue by wioch** [dell/dellemc-openmanage-ansible-modules#50]
Hello,

I'm trying to access VRTX CMC using simple playbook:
```
---
- name: Test CMC connectivity
  hosts: cmc
  connection: local
  gather_facts: false

  tasks:
  - name: Get HW inventory
    dellemc_get_system_inventory:
      idrac_ip: "10.42.163.201"
      idrac_user: "service"
      idrac_pwd: "calvin"
```

However I get following error:
```
TASK [Get HW inventory] ***********************************************************************************************
fatal: [10.42.163.201]: FAILED! => {"changed": false, "msg": "Could not find device driver for iDRAC with IP Address: 10.42.163.201"}
```

Public key has been uploaded to CMC and it works. 
So the question is, is VRTX CMC supported by your Ansible modules ? 

Regards,
