### ISSUE TITLE
[BUG]: Error in idrac_attributes documentation(?)

### ISSUE THREAD

**Issue by knuteriksen** [dell/dellemc-openmanage-ansible-modules#506]
### Bug Description

Not able to set the timezone using the example from [idrac_attributes](https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/modules/idrac_attributes.rst)

Works when changing the uppercase `Z` to lowercase `z`:
`Time.1.TimeZone` -> `Time.1.Timezone`

### Component or Module Name

idrac_attributes

### Ansible Version

2.15.0

### Python Version

3.10

### iDRAC/OME/OME-M version

iDRAC 6.10.80.00

### Operating System

- 

### Playbook Used

From: https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/playbooks/idrac/idrac_attributes.yml
```
- name: Configure the iDRAC attributes for Timezone settings.
      dellemc.openmanage.idrac_attributes:
        idrac_ip: "192.168.0.1"
        idrac_user: "user_name"
        idrac_password: "user_password"
        ca_path: "/path/to/ca_cert.pem"
        idrac_attributes:
          Time.1.TimeZone: CST6CDT
          NTPConfigGroup.1.NTPEnable: Enabled
          NTPConfigGroup.1.NTP1: 192.168.0.5
          NTPConfigGroup.1.NTP2: 192.168.0.6
          NTPConfigGroup.1.NTP3: 192.168.0.7
      tags: timezone-settings
```

### Logs

`fatal: [servername]: FAILED! => {"changed": false, "invalid_attributes": {"Time.1.TimeZone": "Attribute does not exist."}, "msg": "Attributes have invalid values."}`

### Steps to Reproduce

Run the provided playbook

### Expected Behavior

Should be able to set the timezone.

### Actual Behavior

Not able to set the timezone.

### Additional Information

The request payload sent when changing timezone from the GUI uses lowercase `z`:  
`{Attributes: {Time.1.Timezone: "Etc/GMT-2"}}`
