### ISSUE TITLE
[BUG]: ome_application_certificate SAN does not support spaces

### ISSUE THREAD

**Issue by MallocArray** [dell/dellemc-openmanage-ansible-modules#537]
### Bug Description

Recently the ome_application_certificate module was updated to support subject_alternative_names and the examples show a comma separated string with a space after the comma
https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/plugins/modules/ome_application_certificate.py

In my experience, it throws an error if a space is present after the comma, but works if no space is present. This is with OME-M 1.40.20

### Component or Module Name

ome_application_certificate

### Ansible Version

2.14

### Python Version

3.9

### iDRAC/OME/OME-M version

OME-M 1.40.20

### Operating System

Stream 9

### Playbook Used

```yaml
    - name: Generate a certificate signing request.
      dellemc.openmanage.ome_application_certificate:
        hostname: "{{ inventory_hostname }}"
        username: "{{ dell_ome_username }}"
        password: "{{ dell_ome_password }}"
        validate_certs: "{{ dell_validate_certs | default(omit) }}"
        ca_path: "{{ dell_ca_path | default(omit) }}"
        command: "generate_csr"
        distinguished_name: "{{ inventory_hostname }}"
        subject_alternative_names: "{{ subject_alternative_names | default(omit) }}"  # Must also include the distinguished_name in the SAN as one of the options in 8.1 collection
        department_name: "department"
        business_name: "My company"
        locality: "City"
        country_state: "State"
        country: "US"
        email: "address@domain.comt"
      register: csr_result
      tags:
        - csr
```

### Logs

 {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "error_info": {"error": {"@Message.ExtendedInfo": [{"Message": "Unable to complete the request because the input value for Subject Alternative Name(s) is missing or an invalid value is entered.", "MessageArgs": ["Subject Alternative Name(s)"], "MessageId": "CGEN6002", "RelatedProperties": [], "Resolution": "Enter a valid value and retry the operation.", "Severity": "Critical"}], "code": "Base.1.0.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information."}}, "msg": "HTTP Error 400: 400"}

### Steps to Reproduce

Request a CSR where the subject_alternative_names includes a space after the comma, as the examples in the documentation show

`subject_alternative_names: "dellpod23.domain.com, dellpod23chassis01.domain.com"`

### Expected Behavior

CSR is generated without error, with the SANs being added

### Actual Behavior

 {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "error_info": {"error": {"@Message.ExtendedInfo": [{"Message": "Unable to complete the request because the input value for Subject Alternative Name(s) is missing or an invalid value is entered.", "MessageArgs": ["Subject Alternative Name(s)"], "MessageId": "CGEN6002", "RelatedProperties": [], "Resolution": "Enter a valid value and retry the operation.", "Severity": "Critical"}], "code": "Base.1.0.GeneralError", "message": "A general error has occurred. See ExtendedInfo for more information."}}, "msg": "HTTP Error 400: 400"}

### Additional Information

Either the documentation examples should be updated to remove the space, or the module updated to handle spaces without error, or both
