### ISSUE TITLE
dellemc_idrac_user: "Error: 'NoneType' object has no attribute 'iDRAC'"

### ISSUE THREAD

**Issue by mariomelofilho** [dell/dellemc-openmanage-ansible-modules#58]
I'm trying to use dellemc_idrac_user to create/change a user passowrd in idracs and i'm getting bellow erro:

fatal: [localhost -> localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "idrac": null,
            "idrac_ip": "10.99.4.122",
            "idrac_port": 443,
            "idrac_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_user": "root",
            "share_mnt": "/mnt/dell",
            "share_name": "localhost:/mnt/dell",
            "share_pwd": null,
            "share_user": null,
            "state": "present",
            "user_name": "infra",
            "user_priv": "Administrator",
            "user_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "Error: 'NoneType' object has no attribute 'iDRAC'"
}

**Comment by mariomelofilho** [comment]
Versions:
 - iDRAC FW: 2.61.60.60
 - python: 3.6.7
 - omsdk: 1.2.370
 - ansible: 2.8.1

**Comment by anupamaloke** [comment]
@mariomelofilho, The error is due to share_name attribute. You don't have to specify a local directory path with ```"localhost:/"``` prefix, instead you can just provide a linux dir path. For e.g. in the below playbook I am passing in the ```{{ playbok_dir }}``` as the local directory path. Also there is no need to specify ```share_mnt``` when you are using a local directory path. 

```
- name: Configure the modify iDRAC users attributes
    dellemc_configure_idrac_users:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
       share_name: "{{ playbook_dir }}"
       action: "modify"
       user_name: "user_name"
       user_pwd: "{{new_user_password}}"

``` 
Let me know if you still face the issue.
