### ISSUE TITLE
[BUG]: subject_alt_name taking only first item in list

### ISSUE THREAD

**Issue by dbond007** [dell/dellemc-openmanage-ansible-modules#584]
### Bug Description

When generating a csr to be signed only the first item is taken from the list for the SAN ( subject_alt_name taking ).
in the example below, only server.test.com is in the SAN, if they are swapped around only the ip is added.
the has been tested with 

### Component or Module Name

dellemc.openmanage.idrac_certificates

### Ansible Version

core 2.15.6

### Python Version

3.10.12

### iDRAC/OME/OME-M version

IDRAC: 7.00.30.00ansible

### Operating System

Ubuntu 22.04

### Playbook Used

```
- name: Generate HTTPS certificate signing request
  dellemc.openmanage.idrac_certificates:
    idrac_ip: "{{ idrac_ip }}"
    idrac_user: "{{ idrac_username }}"
    idrac_password: "{{ idrac_password }}"
    validate_certs: false
    ca_path: "{{ idrac_cert_ca_certificate }}"
    command: "generate_csr"
    certificate_type: "HTTPS"
    certificate_path: "{{ idrac_cert_https_csr_path }}"
    cert_params:
      common_name: "{{ idrac_cert_common_name }}"
      organization_unit: "{{ idrac_cert_organization_unit }}"
      locality_name: "{{ idrac_cert_locality_name }}"
      state_name: "{{ idrac_cert_state_name }}"
      country_code: "{{ idrac_cert_country_code }}"
      email_address: "{{ idrac_cert_email_address }}"
      organization_name: "{{ idrac_cert_organization_name }}"
      subject_alt_name: "{{ idrac_cert_subject_alt_name }}"
  register: idrac_csr_request_result
  delegate_to: "{{ idrac_management_delegate }}" 
  become: true
  tags: certificate
```
  
  with  
```
 idrac_cert_subject_alt_name:
  - "{{ idrac_cert_common_name }}"
  - "{{ idrac_ip }}"
```

also tried with 
subject_alt_name: "{{ idrac_cert_subject_alt_name | join(',') }}"

both are accepted and show as a list in the debug output, but only the first item is actually used.

### Logs

```
ok: [kub-esxi03i -> localhost] => {
    "certificate_path": "./10.10.17.50_20231122_15350_HTTPS.txt",
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_path": "/home/david/Documents/ansible/roles/ansible-role-idrac_baseline/files/RootCA01.pem",
            "cert_params": {
                "common_name": "server.test.com",
                "country_code": "NO",
                "email_address": "iBBBBB",
                "locality_name": "AAAAAA",
                "organization_name": "EEEEEE",
                "organization_unit": "SSSSSS",
                "state_name": "SSSSSS",
                "subject_alt_name": [
                    "server.test.com",
                    "10.10.17.50"
                ]
            },
            "certificate_path": "./",
            "certificate_type": "HTTPS",
            "command": "generate_csr",
            "idrac_ip": "10.10.17.50",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "root",
            "passphrase": null,
            "reset": true,
            "resource_id": null,
            "timeout": 30,
            "validate_certs": false,
            "wait": 300
        }
    },
    "msg": "Successfully performed the 'generate_csr' operation."
```

### Steps to Reproduce

create a csr with 2 items in the SAN property

### Expected Behavior

all the items should be in the SAN

### Actual Behavior

only the entry in the list first is in the SAN
