### ISSUE TITLE
Updating firmware for HTTP share

### ISSUE THREAD

**Issue by Nathan-UK** [dell/dellemc-openmanage-ansible-modules#60]
Hi,

Just working on testing our code on the 2.01 release and have noticed that there is now no obvious support for updating firmware using a HTTPs share.

Had previously used

> -  name: Update firmware from repository on a HTTP Share
>   dellemc_idrac_firmware:
>     idrac_ip: "{{ iDRAC }}"
>     idrac_user: "{{ idrac_user }}"
>     idrac_pwd: "{{ idrac_pwd }}"
>     share_name: "http://firmware.local.co.uk/PUB/DELL/REPO"
>     catalog_file_name:  "Baseline_1.04_Catalog.xml"
>     apply_update: True
>     reboot: True
>     job_wait: True
> 

using the module from:
https://github.com/dell/dellemc-openmanage-ansible-modules/blob/bd29724dca151d9aead0f5e597939b5ee0ae3ee4/library/dellemc/idrac/dellemc_idrac_firmware.py

was going to update to idrac_firmware but that needs read write permissions on the share?!?

Nathan

**Comment by rajshekarp87** [comment]
@Nathan-UK,

Thanks for trying out Dell EMC OpenMange Ansible modules.

As you aware, latest version (2.0.1) of `idrac_firmware` module does not have support for HTTPS share. We do support CIFS/NFS share with Read/Write permission.

The previous `dellemc_idrac_firmware` module which you have used for updating from a HTTPS share is from one of our branch `fw_update_url` which is still available and is compatible with omsdk `fw_update_url`  branch (https://github.com/dell/omsdk/tree/fw_update_url).

-Rajshekar P

**Comment by Nathan-UK** [comment]
Is there any plans to bring this back into the main version of this as it mimic the native abilities of iDRAC updating form a HTTP repo?

**Comment by anupamaloke** [comment]
@Nathan-UK, you can use ```idrac_firmware``` module from the [fw_update_url](https://github.com/dell/dellemc-openmanage-ansible-modules/tree/fw_update_url) branch for firmware update using a HTTP(S) repository. In the latest version, ```share_name``` argument now accept a domain name (for e.g. http://downloads.dell.com) in addition to an IPv4 address. 

In order to use the ```idrac_firmware``` module from ```fw_update_url``` branch, you need do the following:
```
git clone https://github.com/dell/dellemc-openmanage-ansible-modules.git
cd dellemc-openmanage-ansible-modules
git checkout fw_update_url
python install.py
```

Following playbook will update your servers with latest firmware from Dell online repository (downloads.dell.com):
``` 
- name: Update firmware from repository on a HTTP/S Share
  idrac_firmware:
    idrac_ip: "192.168.10.1"
    idrac_user: "user_name"
    idrac_password: "user_pwd"
    share_name: "http://downloads.dell.com/catalog"
    catalog_file_name: "catalog.xml"
    apply_update: True
    reboot: True
    job_wait: True
  delegate_to: localhost
```
