### ISSUE TITLE
[QUESTION]: openmanage.ome_discovery always uses SSH(?)

### ISSUE THREAD

**Issue by gilfalko** [dell/dellemc-openmanage-ansible-modules#606]
I copied the following example from the official documentation:

```
- name: Discover servers in a range
  dellemc.openmanage.ome_discovery:
    hostname: "192.168.0.1"
    username: "username"
    password: "password"
    #ca_path: "/path/to/ca_cert.pem"
    discovery_job_name: "Discovery_server_1"
    discovery_config_targets:
    validate_certs: false
      - network_address_detail:
          - 192.96.24.1-192.96.24.255
        device_types:
          - SERVER
        wsman:
          username: user
          password: password

```
My issue is that this task attempts to connect with SSH to my inventory host for some reason. My inventory host for this purpose is an IDRAC server. I have no idea why it does that when the Playbook has **"gather_facts: no"**.
