### ISSUE TITLE
[QUESTION]: How to use the roles

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#613]
### How can the team help?

Hello im probably coming with the silly question but can you pls elaborate on how i can use  for example this role ?

```
- name: Restart the idrac and wait for the idrac to be ready
  ansible.builtin.include_role:
    name: idrac_reset       
  vars:
    hostname: "192.168.0.1"
    username: "username"
    password: "password"


```

Im getting error - role not found in path unless i specify full path to the openmanage collection in ansible.cfg 

`roles_path = ~/.ansible/collections/ansible_collections/dellemc/openmanage/roles
`
is that a hard requirement as i didnt see that anywhere in documentation ?
