### ISSUE TITLE
Convert module parameters to module variables

### ISSUE THREAD

**Issue by johnrmiller** [dell/dellemc-openmanage-ansible-modules#62]
Hi folks,

It's a little crazy that I need to pass in a username, password, and IP/FQDN into the openmanage modules every single time that I invoke them.  That information is already taken care of by `ansible_user`.  Likewise with the hostname/IP: that's part of my inventory.  Please update the modules to convert the module parameters to variables, as is done with mainline Ansible modules.

**Comment by anupamaloke** [comment]
@johnrmiller, you can use the ansible variables in your playbook with iDRAC or OpenManage Enterprise modules. For e.g.

**[inventory]**
```
[idracs]
192.168.1.1  ansible_user="root" ansible_connection=local

[ome]
192.168.1.2 ansible_user="admin" ansible_connection=local
``` 

**[Playbook]**

```
- hosts: idracs
  gather_facts: False

  tasks:
  - name: Get system inventory
    dellemc_get_system_inventory:
      idrac_ip:  "{{ inventory_hostname }}"
      idrac_user:  "{{ ansible_user }}"
      idrac_password:  "{{ idrac_password }}"

- hosts: ome
  gather_facts: False

  tasks:
  - name: Get the device inventory
    dellemc_ome_device_facts:
      hostname: "{{ inventory_hostname }}"
      username:  "{{ ansible_user }}"
      password:  "{{ ome_password }}"
```
