### ISSUE TITLE
[QUESTION]: Does the module idrac_certificates module works only one host at a time ?

### ISSUE THREAD

**Issue by avijitkulkarni30** [dell/dellemc-openmanage-ansible-modules#672]
### How can the team help?

**Details: ?**
Hello Team,
dellemc.openmanage.idrac_certificates: Limiting playbook with multiple hostnames fails and only one host completes successfully every time and the remaining fails.
Is this a limitation in the module ?
Thank you.

**Comment by anupamaloke** [comment]
@avijitkulkarni30, the iDRAC ansible modules work with one iDRAC at a time. If you want to run the same task on multiple iDRACs, then you will have to setup ansible inventory accordingly. For e.g., following is a simple inventory that has a list of iDRACs grouped under the `idrac` host group. For more details on inventory, please see https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html.

**inventory**
```
---
[idracs]
10.0.0.1
10.0.0.2
10.0.0.3
```

**playbook.yml**
```
---
- hosts: idracs
  gather_facts: no

  tasks:
  - name: Import a certificate.
    ansible.builtin.import_role:
      name: idrac_certificate
    vars:
      hostname: "{{ inventory_hostname }}"
      username: "{{ idrac_username }}"
      password: "{{ idrac_password }}"
      ca_path: "/path/to/ca_cert.pem"
      command: "import"
      certificate_type: "HTTPS"
      certificate_path: "/path/to/cert.pem"
```

**Running the playbook**
```
$ ansible-playbook -vvv playbook.yml -i inventory
```
