### ISSUE TITLE
dellemc_configure_idrac_users : custom privileges

### ISSUE THREAD

**Issue by an-t-oine** [dell/dellemc-openmanage-ansible-modules#69]
is there a way to create custom privileges instead of "Administrator/Operator/Readonly/No-Access" ? 

My goal is to create on readonly role with the privilege to launch virtual console.

With UI, you can do that by attribute the Readonly privilege to a user and then modify by checking the box for launch virtual console.

**Comment by wioch** [comment]
Do you mean this:
```
<Attribute Name="Users.9#Privilege">499</Attribute>
```
?

**Comment by an-t-oine** [comment]
i'm sorry, i don't understant your answer.
I want to create a new role with custom privileges OR customize an existing role.
In the screenshot here [,](https://ibb.co/JyFcHJY) i customize "operator" role. But i can do that with GUI not with CLI.

**Comment by wioch** [comment]
I meant this:
```
<SystemConfiguration>
<Component FQDD="iDRAC.Embedded.1">
 <Attribute Name="Users.9#UserName">someuser</Attribute>
 <Attribute Name="Users.9#Privilege">499</Attribute>
 <Attribute Name="Users.9#IpmiLanPrivilege">No Access</Attribute>
 <Attribute Name="Users.9#IpmiSerialPrivilege">No Access</Attribute>
 <Attribute Name="Users.9#Enable">Enabled</Attribute>
 <Attribute Name="Users.9#SolEnable">Disabled</Attribute>
 <Attribute Name="Users.9#ProtocolEnable">Disabled</Attribute>
 <Attribute Name="Users.9#AuthenticationProtocol">SHA</Attribute>
 <Attribute Name="Users.9#PrivacyProtocol">AES</Attribute>
 <Attribute Name="Users.9#Password">somepass</Attribute>
</Component>
</SystemConfiguration>
````

with this:
```
---
- name: Create users (keyuser,snmpv3user, tier2) on iDRAC
  idrac_server_config_profile:
    idrac_ip: "1.1.1.1"
    idrac_user: "root"
    idrac_password: "rootpass"
    idrac_port: "443"
    command: "import"
    share_name: "1.1.1.2:/nfs_share"
    scp_file: "idrac_add_users.xml"
    scp_components: "ALL"
    job_wait: True
```

All you have to do is to set privileges as a number.
I cannot tell you how to convert privileges to number (it has something to do with binary), but you can create a user with privileges you want, dump config, get the number from that config. 
I hope that's clear now.
