### ISSUE TITLE
[BUG]: Virtual media support in idrac_boot doesn't work for iDrac8

### ISSUE THREAD

**Issue by coffee-driven** [dell/dellemc-openmanage-ansible-modules#693]
### Bug Description

Here is way of forcing boot from virtual media found in this feature request https://github.com/dell/dellemc-openmanage-ansible-modules/issues/457 But it doesn't work as expected, it does select CD installation but not "Virtual Optical Drive" but probably physical CD.

```
  - name: Configure boot source override mode.
    idrac_boot:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: false
      boot_source_override_target: cd
      boot_source_override_enabled: once
    tags: virtual-cd`
```
    

### Component or Module Name

idrac_boot

### Ansible Version

2.15.11

### Python Version

3.11.2

### iDRAC/OME/OME-M version

iDRAC 2.86.86.86

### Operating System

OS independent

### Playbook Used

```
- name: Install from Virtual CD
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Insert image file to Remote File Share using HTTP.
      dellemc.openmanage.idrac_virtual_media:
        idrac_ip: "192.168.0.1"
        idrac_user: "root"
        idrac_password: "calvin"
        validate_certs: false
        force: true
        virtual_media:
          - index: 1
            insert: true
            media_type: "CD"
            image: "http://192.168.0.2/my_os.iso"

    - dellemc.openmanage.idrac_boot:
        idrac_ip: "192.168.0.1"
        idrac_user: "root"
        idrac_password: "calvin"
        boot_source_override_mode: uefi
        boot_source_override_target: cd
        boot_source_override_enabled: once
        validate_certs: false
```

### Logs

```
PLAY [Install via Virtual CD] *************************************************************************************

TASK [Insert image file to Remote File Share using HTTP] *********************************************************************
changed: [localhost]

TASK [dellemc.openmanage.idrac_boot] ******************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

### Steps to Reproduce

Run the playbook against server.

### Expected Behavior

Server boot from Virtual CD

### Actual Behavior

Physical CD is selected, server boots from other available methods.

### Screenshots

![image](https://github.com/dell/dellemc-openmanage-ansible-modules/assets/35033056/976c6954-f284-4d90-86ec-bb21a481c1bd)

### Additional Information

The server is Dell R730xd
