### ISSUE TITLE
[QUESTION]: SecureErase issue erasing multiple drives

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#708]
### Bug Description

im getting error when trying to erase multiple drives. 
according to manual the option target is the 
list / elements =string

### Component or Module Name

idrac_redfish_storage_controller

### Ansible Version

Ansible 2.17.1

### Python Version

Python 3.11.7

### iDRAC/OME/OME-M version

idrac 6.10.80

### Operating System

N/A

### Playbook Used

```
- name: Perform Secure Erase operation on SED drive
  dellemc.openmanage.idrac_redfish_storage_controller:
    baseuri: "{{ alv_lom_ip }}"
    username: "{{ lom_username }}"
    password: "{{ lom_password }}"
    controller_id: "RAID.Integrated.1-1"
    command: "SecureErase"
    target: ['Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1', 'Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1']
```

### Logs

fatal: [localhost]: FAILED! => {"changed": false, "msg": "The Fully Qualified Device Descriptor (FQDD) of the target physical disk must be only one."}

### Steps to Reproduce

run the playbook

### Expected Behavior

erase all the drives

### Actual Behavior

error message
