### ISSUE TITLE
[BUG]: Module 8.7.0, idrac_gather_facts role and iDrac8 (2.84.84.84)

### ISSUE THREAD

**Issue by stf1966** [dell/dellemc-openmanage-ansible-modules#718]
### Bug Description

Testing the role idrac_gather_facts with different role target...
- target: BIOS,CPU,Firmware,HostNIC,Memory,NIC works correctly on iDrac v8 and v9
- target: IDRAC, System, Enclosure doesn't works on iDrac v8 ??? ok on v9

In fact, there isn't https://xxxxxx/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1 on v8
Perhaps I misunderstand the documentation "Dell OpenManage Ansible Modules 8.7.0"
Supported Platforms
iDRAC8 based Dell PowerEdge Servers with firmware versions 2.84.84.84 and above.

### Component or Module Name

idrac_gather_facts role

### Ansible Version

Ansible 2.16.9

### Python Version

Python 3.10.12

### iDRAC/OME/OME-M version

iDRAC8 firm 2.84.84.84

### Operating System

Ubuntu 22.04

### Playbook Used

- name: "Let's play with idrac_gather_facts role..."
  hosts: idrac
  connection: local
  gather_facts: false
  collections:
  - dellemc.openmanage
  vars_prompt:
  - name: idrac_pwd
    prompt: Please provide your idrac password
    private: true

  tasks:
  - name: iDRAC gather facts for System, BIOS, Controller, CPU, Enclosure.
    ansible.builtin.import_role: 
      name: idrac_gather_facts
    vars:
      validate_certs: false    
      hostname: "{{ ansible_host }}"
      username: "{{ idrac_user }}"
      password: "{{ idrac_pwd }}"
      # ca_path: "/path/to/ca_cert.pem"
      target:
      - IDRAC #or System or Enclosure, or Controller
  - ansible.builtin.debug: var=idrac

### Logs

fatal: [S22914]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'Attributes'. 'dict object' has no attribute 'Attributes'\n\nThe error appears to be in '/usr/lib/python3/dist-packages/ansible_collections/dellemc/openmanage/roles/idrac_gather_facts/tasks/get_attributes_info.yml': line 23, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set System, Manager, Lifecycle controller facts\n  ^ here\n"}

### Steps to Reproduce

just a basic playbook to import the role idrac_gather_facts

### Expected Behavior

success

### Actual Behavior

Failed

**Comment by akire0ne** [comment]
We have a similiar issue here. R630 w/ Idrac8 running `2.85.85.85` fw. 
We cannot gather facts on the `System` target. Other targets (see example above) just run as fine.

```
---
- name: Test idrac role
  gather_facts: false
  hosts: XXXX
  roles:
    - role: dellemc.openmanage.idrac_gather_facts
      vars:
        hostname: XXXXX
        username: XXXXXX
        password: XXXXX
        validate_certs: false
        target:
          # - System
          - Firmware
          - BIOS
          - CPU
          - Memory
          - NIC
          - PhysicalDisk
```

it seems the JSON returned by the System endpoint does not match the expected structure of the role.
The role tries to parse `system_result.json.Oem.Dell.DellSystem` but the returned JSON does not contain an `Oem` key.

For me it looks like `System` does not support IDRAC8.
