### ISSUE TITLE
[QUESTION]:How do i update the iDRAC hostname, tried dellemc.openmanage.idrac_attributes but doesn't work 

### ISSUE THREAD

**Issue by mparmar-pure** [dell/dellemc-openmanage-ansible-modules#732]
How do i update the iDRAC hostname, tried dellemc.openmanage.idrac_attributes

```
    - name: Configure new iDRAC hostname
      loop: "{{ gsheet_device_list.stdout }}"
      delegate_to: localhost
      dellemc.openmanage.idrac_attributes:
          idrac_ip: "{{ item[1] }}"
          idrac_user: "{{ idrac_username }}"
          idrac_password: "{{ idrac_password }}"
          validate_certs: False
          system_attributes:
              ServerOS.1.HostName: "{{ item[0]|lower }}-ipmi.{{ system_domain }}"
```
It is updating the property for ServerOS.1.HostName":"test.domain" but entry under iDRAC --> Connectivity --> 
DNS iDRAC Name* does not change and hence i am not able to log in using new domain address
