### ISSUE TITLE
dellemc_ome_template attribute Networkbootisomodel not work

### ISSUE THREAD

**Issue by gisyrus** [dell/dellemc-openmanage-ansible-modules#76]
I tried to automate the os deployment by using dellemc_ome_template module. However, the module doesn't work at all. The job is successfully created but when it finish the hareware configuration and go to boot the network iso, an error message will be shown:

```
 ====== Starting Boot to Network ISO ======
....Boot to Network ISO is in progress.It will take few minutes to complete.
....Inaccessible network share.
....Boot to Network ISO failed.
Failed to perform Boot to Network ISO
Task Failed. Completed With Errors. 
```

I have checked with the module dellemc_boot_to_network_iso and I can successfully deploy the os using the iDRAC module. 

Here is my playbook:

```yml
-
  hosts: omeserver
  gather_facts: false
  connection: local
  tasks:
    - name: deploy template.
      dellemc_ome_template:
        hostname: "{{ ome_ipaddress }}"
        username: "{{ ome_username }}"
        password: "{{ ome_password }}"
        state: "deploy"
        template_id: 19
        device_service_tag: '123A456'
        attributes:
          NetworkBootIsoModel:
            BootToNetwork: true
            ShareType: "NFS"
            IsoPath: "boottoiso.iso"
            ShareDetail:
              IpAddress: "10.222.198.19"
              ShareName: "/home/iso"
              User: "root"
              Password: "password"
          Options:
            EndHostPowerState: 1
            ShutdownType: 0
            TimeToWaitBeforeShutdown: 300
          Schedule:
            RunLater: false
            RunNow: true
      register: output
    - name: debug
      debug:
        var: output
```

Does anyone get idea what's going on?

**Comment by gisyrus** [comment]
And the version of my module is 2.0.1 . Does it matter?

**Comment by rajshekarp87** [comment]
Hi Gisyrus,

Input for options "IsoPath" and "ShareName" should be in below format. With below modifications, issue will not be observed.

**"IsoPath" : /home/iso/bootoiso.iso"** ; Complete iso path
**"ShareName" : "iso"** ; Share name

Thanks & Regards,
Rajshekar P

**Comment by rajeevarakkal** [comment]
@gisyrus Any update on this?

**Comment by gisyrus** [comment]
@rajshekarp87 @rajeevarakkal 
Yes it is correct.
IsoPath represents the full path where the iso is located at and ShareName represents the folder that containing the iso image.
However, in the example of the module it states like this:
```yml
- name: deploy template.
    dellemc_ome_template:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      state: "deploy"
      template_id: 1234
      device_id:
        - 12345
        - 45678
      device_service_tag: ['SVTG123', 'SVTG456']
      attributes: # All options for deploy operation
        NetworkBootIsoModel:
          BootToNetwork: false
          ShareType: "NFS"
          IsoPath: "bootToIsoPath.iso"
          ShareDetail:
            IpAddress: "192.168.0.2"
            ShareName: "/nfsshare"
            User: null
            Password: null
        Attributes:
          - DeviceId: 12345
            Attributes :
              - Id : 123
                Value : "0.0.0.0"
                IsIgnored : true
        Options:
          EndHostPowerState: 1
          ShutdownType: 0
          TimeToWaitBeforeShutdown: 300
        Schedule:
          RunLater: true
          RunNow: false
```

It is somehow misleading to the user that they will think IsoPath represents the name of iso image and ShareName represents the complete iso path.

Can you edit the example so that the future users will not get the same fault? Thank you very much for your help.
