### ISSUE TITLE
Update idrac_os_deployment to support Redfish

### ISSUE THREAD

**Issue by tsquillario** [dell/dellemc-openmanage-ansible-modules#85]
This module should support mounting VirtualMedia and setting the OneTime boot device over Redfish.

**Comment by rajeevarakkal** [comment]
@tsquillario We will check the feasibility and timeline to enable this featre

**Comment by anupamaloke** [comment]
@tsquillario, Virtual Media support has now been enabled in the [redfish_command.py](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/remote_management/redfish/redfish_command.py). In order to use the virtual media commands, please make sure that you install community.general ansible collection using `ansible-galaxy` CLI:

```
ansible-galaxy collection install community.general
```
You can also include it in a ```requirements.yml``` file and install it via ```ansible-galaxy collection install -r requirements.yml``` using the format:
```
collections:
- name: community.general
```
See [Ansible Using collections](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html) for more details.

Following commands are supported for virtual media:

- **Insert Virtual Media**
```
  - name: Insert Virtual Media
    community.general.redfish_command:
      category: Manager
      command: VirtualMediaInsert
      baseuri: "{{ idrac_ip }}"
      username: "{{ idrac_user}}"
      password: "{{ idrac_password }}"
      virtual_media:
        image_url: 'http://example.com/images/SomeLinux-current.iso'
        media_types:
          - CD
          - DVD
      resource_id: iDRAC.Embedded.1
```
- **Eject Virtual Media**
```
  - name: Eject Virtual Media
    community.general.redfish_command:
      category: Manager
      command: VirtualMediaEject
      baseuri: "{{ idrac_ip }}"
      username: "{{ idrac_user }}"
      password: "{{ idrac_password }}"
      virtual_media:
        image_url: 'http://example.com/images/SomeLinux-current.iso'
      resource_id: iDRAC.Embedded.1
```

**Comment by ykorzikowski** [comment]
Hi there, 

we are trying this role to install our server. The issue we are getting now: The server is booting in loop from the installation iso. Only when you eject it manually, Its booting from the harddisk again. Does anybody know how to solve this issue?

```
- hosts: idrac
  connection: local
  name: Get system inventory
  gather_facts: False

  collections:
    - community.general
  tasks:
    - name: Insert Virtual Media
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaInsert
        baseuri: "{{ ansible_host }}" 
        username: "{{ idrac_user}}" 
        password: "{{ idrac_password }}" 
        virtual_media:
          image_url: "{{ file_location }}"
          media_types:
            - CD
            - DVD
        resource_id: iDRAC.Embedded.1

    - name: Set one-time boot device to cd
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: "Cd"
        baseuri: "{{ ansible_host }}"
        username: "{{ idrac_user }}"
        password: "{{ idrac_password }}"

    - name: Reboot system power
      community.general.redfish_command:
        category: Systems
        command: PowerReboot
        baseuri: "{{ ansible_host }}" 
        username: "{{ idrac_user}}" 
        password: "{{ idrac_password }}" 
```
