### ISSUE TITLE
[ENHANCEMENT]: idrac_system_erase status not failed

### ISSUE THREAD

**Issue by markatdxb** [dell/dellemc-openmanage-ansible-modules#866]
### Bug Description

I ran this module with job_wait: true leaving job_wait_timeout default value 1200. 
after 1200 sec job was marked as changed and playbook continued

Issue is that later on i found out that job actually didnt finish and data were not cleared

### Component or Module Name

idrac_system_erase

### Ansible Version

Ansible 2.17

### Python Version

Python 3.12

### iDRAC/OME/OME-M version

iDRAC 9 - 7.20.10.05

### Operating System

Windows OS

### Playbook Used

```
- name: IDRAC9  system wipe
      dellemc.openmanage.idrac_system_erase:
        idrac_ip: "{{ lom_ip }}"
        idrac_user: "{{ lom_username }}"
        idrac_password: "{{ lom_password }}"
        validate_certs: false
        component:
          - AllApps
          - BIOS
          - CryptographicErasePD
          - DIAG
          - DPU
          - DrvPack
          - NonVolatileMemory
          - OverwritePD
          - PERCNVCache
          - ReinstallFW
```

### Logs

```
{
    "msg": "The job is not complete after 1200 seconds.",
    "changed": true,
    "job_status": {
        "ActualRunningStartTime": "2025-04-08T11:17:23",
        "ActualRunningStopTime": 0,
        "CompletionTime": null,
        "Description": "Job Instance",
        "EndTime": "TIME_NA",
        "Id": "JID_441110378025",
        "JobState": "Running",
        "JobType": "SystemErase",
        "Message": "Some of the DPU devices data were failed to reset",
        "MessageArgs": [],
        "MessageId": "SYS560",
        "Name": "System_Erase",
        "PercentComplete": 10,
        "StartTime": "2025-04-08T11:17:17",
        "TargetSettingsURI": null
    },
    "invocation": {
        "module_args": {
            "idrac_ip": "10.10.10.10",
            "idrac_user": "user",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false,
            "component": [
                "AllApps",
                "BIOS",
                "CryptographicErasePD",
                "DIAG",
                "DPU",
                "DrvPack",
                "NonVolatileMemory",
                "OverwritePD",
                "PERCNVCache",
                "ReinstallFW"
            ],
            "power_on": false,
            "job_wait": true,
            "job_wait_timeout": 1200,
            "idrac_port": 443,
            "timeout": 30,
            "resource_id": null,
            "x_auth_token": null,
            "ca_path": null
        }
    },
    "_ansible_no_log": false
}
```

### Steps to Reproduce

use above task

### Expected Behavior

process fails after 1200 sec timeout 

### Actual Behavior

process continues marked as changed
