### ISSUE TITLE
[QUESTION]: idrac_os_deployment role -- Unable to complete the virtual media operation.

### ISSUE THREAD

**Issue by FunSkiDry** [dell/dellemc-openmanage-ansible-modules#874]
I'm trying to use the idrac_os_deployment role to deploy Proxmox to my Dell PowerEdge R630 iDRAC8 	
2.86.86.86 server.  I tried using the example playbooks in the git repo as a starter point but I encounter a generic server error with no further details to chase down.  What am I doing wrong with this playbook?

```
---
- name: configure Proxmox
  hosts: proxmox
  gather_facts: false

  collections:
    - dellemc.openmanage

  vars_prompt:
    - name: idrac_password
      prompt: idrac_password
      private: true

  tasks:

    - name: Deploy Proxmox using iDRAC OS Deployment
      include_role:
        name: dellemc.openmanage.idrac_os_deployment
      vars:
        hostname: "{{ ip }}"
        username: "{{ idrac_user }}"
        password: "{{ idrac_password }}"
        validate_certs: false
        source:
          hostname: "enterprise.proxmox.com"
          iso_path: "/iso"
          iso_name: "proxmox-ve_8.4-1.iso"
          protocol: https
          is_custom_iso: true
        wait_for_os_deployment: true
        os_deployment_timeout: 60  # minutes to wait for OS deployment

```

TASK [dellemc.openmanage.idrac_os_deployment : Attach the iso to Virtual Media slot 1] ****************************************************************************************************************
task path: /home/user/.ansible/collections/ansible_collections/dellemc/openmanage/roles/idrac_os_deployment/tasks/idrac/attach_iso_to_virtual_media.yml:23

fatal: [10.40.15.10 -> localhost]: FAILED! => {
    "changed": false,
    "error_info": [
        {
            "@Message.ExtendedInfo": [
                {
                    "Message": "The request failed due to an internal service error.  The service is still operational.",
                    "MessageArgs": [],
                    "MessageArgs@odata.count": 0,
                    "MessageId": "Base.1.2.InternalError",
                    "RelatedProperties": [],
                    "RelatedProperties@odata.count": 0,
                    "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service.",
                    "Severity": "Critical"
                }
            ],
            "code": "Base.1.2.GeneralError",
            "message": "A general error has occurred. See ExtendedInfo for more information"
        }
    ],
    "invocation": {
        "module_args": {
            "ca_path": null,
            "force": true,
            "idrac_ip": "10.40.15.10",
            "idrac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "idrac_port": 443,
            "idrac_user": "root",
            "resource_id": null,
            "timeout": 30,
            "validate_certs": false,
            "virtual_media": [
                {
                    "domain": null,
                    "image": "https://enterprise.proxmox.com/iso/proxmox-ve_8.4-1.iso",
                    "index": null,
                    "insert": true,
                    "media_type": null,
                    "password": null,
                    "username": null
                }
            ],
            "x_auth_token": null
        }
    },
    "msg": "Unable to complete the virtual media operation."
}
