### ISSUE TITLE
'iDRACEntity' object has no attribute '_get_update_from_repo_list_using_redfish'

### ISSUE THREAD

**Issue by manualbashing** [dell/dellemc-openmanage-ansible-modules#88]
I keep running into the following error, when I try to update firmware on R740 servers, using a CIFS share:

```
/dellemc/idrac_firmware.py", line 314, in update_firmware
AttributeError: 'iDRACEntity' object has no attribute '_get_update_from_repo_list_using_redfish'
fatal: [192.168.1.100 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/abtis/.ansible/tmp/ansible-tmp-1574946961.161-121069216090102/AnsiballZ_idrac_firmware.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/abtis/.ansible/tmp/ansible-tmp-1574946961.161-121069216090102/AnsiballZ_idrac_firmware.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/abtis/.ansible/tmp/ansible-tmp-1574946961.161-121069216090102/AnsiballZ_idrac_firmware.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.remote_management.dellemc.idrac_firmware', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_idrac_firmware_payload_hesd_lt7/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py\", line 378, in <module>\n  File \"/tmp/ansible_idrac_firmware_payload_hesd_lt7/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py\", line 366, in main\n  File \"/tmp/ansible_idrac_firmware_payload_hesd_lt7/ansible_idrac_firmware_payload.zip/ansible/modules/remote_management/dellemc/idrac_firmware.py\", line 314, in update_firmware\nAttributeError: 'iDRACEntity' object has no attribute '_get_update_from_repo_list_using_redfish'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

My task looks like this:

```yaml
- name: Update firmware
  idrac_firmware:
    idrac_ip: "192.168.1.100"
    idrac_user: "root"
    idrac_password: "{{ idrac_pass }}"
    share_name: "\\\\192.168.1.11\\dell"
    share_user: "dell"
    share_password: "{{ firmware_share_pass }}"
    share_mnt: /tmp/dell
    reboot: True
    job_wait: True
    apply_update: True
    catalog_file_name: "Catalog.xml"
  delegate_to: localhost
```

The CIFS share is mounted with rw permission to the ansible node in the path `/tmp/dell`.
